<?php
/** Production chat-route regressions for server-owned generated-copy intake.
 * Included by flex-generation-runtime.php after the chat harness and route factory exist.
 */

$intake_hero_prompt = 'Создай Hero для небольшой архитектурной студии, которая проектирует частные дома и общественные пространства. Напиши заголовок и описание на основе этого задания, без фото, цифр, обещаний и выдуманных достижений. CTA «Обсудить проект» → #contact.';
$intake_hero_response = [
	'family' => 'hero',
	'generated' => [
		[ 'slot_id' => 'section_title', 'text' => 'Архитектура для жизни и встреч', 'fact_refs' => [] ],
		[ 'slot_id' => 'section_intro', 'text' => 'Проектируем частные дома и общественные пространства с вниманием к задачам места и повседневному использованию.', 'fact_refs' => [] ],
	],
];
$intake_hero = $run_services_route( $intake_hero_prompt, [ provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-generated-hero' );
$intake_hero_pipeline = (array) ( $intake_hero['response']['diagnostics']['design_pipeline'] ?? [] );
check( ! empty( $intake_hero['response']['ok'] ), 'Ordinary plugin chat accepts generated Hero copy through the production intake: ' . wp_json_encode( $intake_hero['error'], JSON_UNESCAPED_UNICODE ) );
check( $intake_hero['calls'] === 1 && $intake_hero['writes'] === 1 && $intake_hero['write_attempts'] === 1 && ( $intake_hero['response']['diagnostics']['provider_calls'] ?? -1 ) === 1, 'Generated Hero uses one typed provider intake and one transaction only' );
check( ( $intake_hero_pipeline['brief']['intake']['source'] ?? '' ) === 'provider_typed_intake' && ( $intake_hero_pipeline['brief']['intake']['provider_calls'] ?? -1 ) === 1 && ( $intake_hero_pipeline['brief']['hash'] ?? '' ) === ( $intake_hero_pipeline['plan']['brief_hash'] ?? '' ), 'Generated Hero freezes one provider-derived Brief consumed by its accepted Plan' );

$intake_live_hero_prompt = 'Создай самостоятельный блок Hero для небольшой архитектурной и интерьерной студии. Сформулируй оригинальный заголовок и короткое описание: студия проектирует жилые пространства от планировочной идеи до понятной документации, учитывая дневной свет, повседневное движение и хранение. Это весь набор разрешённых фактов о тестовой студии. Не добавляй цифры, сроки, опыт, клиентов, награды, географию, гарантии, цены или обещания. Заголовок и описание должны быть написаны моделью; готовых строк для них нет. Добавь одну основную кнопку с точным текстом «Обсудить проект» и точной ссылкой #contact. Без изображения и без второй кнопки. Композиция — автоматически. Добавь блок к существующей странице.';
$intake_live_hero = $run_services_route( $intake_live_hero_prompt, [ provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-live-natural-hero-cta' );
$intake_live_hero_pipeline = (array) ( $intake_live_hero['response']['diagnostics']['design_pipeline'] ?? [] );

$intake_plan_refusal_prompt = 'Создай Hero для архитектурной студии. Оставь точную фразу «Только по записи» как дополнительный текст, а заголовок и описание напиши по заданию: проектирование жилых пространств с учётом света и хранения.';
$intake_plan_refusal = $run_services_route( $intake_plan_refusal_prompt, [ provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-plan-refusal-telemetry' );
$intake_plan_refusal_details = (array) ( $intake_plan_refusal['error']['data']['details'] ?? [] );
check( ( $intake_plan_refusal['error']['code'] ?? '' ) === 'wpae_design_plan_rejected' && $intake_plan_refusal['calls'] === 1 && $intake_plan_refusal['writes'] === 0 && $intake_plan_refusal['roots'] === array_column( $legacy_page, 'id' ) && ( $intake_plan_refusal_details['provider_calls'] ?? -1 ) === 1 && ( $intake_plan_refusal_details['provider_call_count_source'] ?? '' ) === 'canonical_intake_telemetry' && ( $intake_plan_refusal_details['intake']['provider_calls'] ?? -1 ) === 1, 'Downstream Plan refusal preserves actual canonical-intake provider-call telemetry and remains no-write' );

$intake_collect_strings = static function ( array $nodes ) use ( &$intake_collect_strings ): array {
	$strings = [];
	foreach ( $nodes as $node ) {
		if ( ! is_array( $node ) ) { continue; }
		$settings = (array) ( $node['settings'] ?? [] );
		foreach ( [ 'title', 'editor', 'text', 'url' ] as $key ) { if ( is_string( $settings[ $key ] ?? null ) ) { $strings[] = wp_strip_all_tags( (string) $settings[ $key ] ); } }
		if ( is_array( $settings['link'] ?? null ) && is_string( $settings['link']['url'] ?? null ) ) { $strings[] = (string) $settings['link']['url']; }
		foreach ( (array) ( $settings['tabs'] ?? [] ) as $tab ) { if ( is_array( $tab ) ) { $strings[] = (string) ( $tab['tab_title'] ?? '' ); $strings[] = wp_strip_all_tags( (string) ( $tab['tab_content'] ?? '' ) ); } }
		$strings = array_merge( $strings, $intake_collect_strings( (array) ( $node['elements'] ?? [] ) ) );
	}
	return array_values( array_filter( $strings, static fn( string $value ): bool => $value !== '' ) );
};

$intake_live_hero_strings = $intake_collect_strings( [ $intake_live_hero['written'] ] );
check( ! empty( $intake_live_hero['response']['ok'] ) && $intake_live_hero['calls'] === 1 && $intake_live_hero['writes'] === 1 && in_array( 'Обсудить проект', $intake_live_hero_strings, true ) && in_array( '#contact', $intake_live_hero_strings, true ) && empty( array_filter( (array) ( $intake_live_hero_pipeline['plan']['validation']['errors'] ?? [] ), static fn( string $error ): bool => $error === 'unbound_explicit_content:text' ) ), 'Ordinary plugin chat binds natural exact CTA language before the generated Hero Plan freezes: ' . wp_json_encode( [ 'error' => $intake_live_hero['error'], 'calls' => $intake_live_hero['calls'], 'writes' => $intake_live_hero['writes'], 'native_strings' => $intake_live_hero_strings, 'plan_errors' => $intake_live_hero_pipeline['plan']['validation']['errors'] ?? [] ], JSON_UNESCAPED_UNICODE ) );

$intake_unknown_prompt = 'Создай визуальный фрагмент с заголовком и коротким пояснением для архитектурного бюро. Не добавляй фото.';
$intake_unknown_probe = wpae_brief_ir_parse( $intake_unknown_prompt );
$intake_unknown_response = [ 'family' => 'hero', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Пространство, созданное для людей', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Проектируем частные дома и общественные пространства, учитывая задачи места и повседневную жизнь.', 'fact_refs' => [] ] ] ];
$intake_unknown = $run_services_route( $intake_unknown_prompt, [ provider_reply( wp_json_encode( $intake_unknown_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-classified-freeform' );
$intake_unknown_pipeline = (array) ( $intake_unknown['response']['diagnostics']['design_pipeline'] ?? [] );
check( ( $intake_unknown_probe['intent']['archetype'] ?? '' ) === 'unknown' && ! empty( $intake_unknown['response']['ok'] ) && $intake_unknown['calls'] === 1 && $intake_unknown['writes'] === 1 && ( $intake_unknown_pipeline['brief']['archetype'] ?? '' ) === 'hero' && ( $intake_unknown_pipeline['brief']['hash'] ?? '' ) === ( $intake_unknown_pipeline['plan']['brief_hash'] ?? '' ), 'Ordinary one-line free-form chat classifies once into a supported family, then freezes one Brief for the Plan: ' . wp_json_encode( [ 'probe_family' => $intake_unknown_probe['intent']['archetype'] ?? '', 'error' => $intake_unknown['error'], 'calls' => $intake_unknown['calls'], 'brief_family' => $intake_unknown_pipeline['brief']['archetype'] ?? '', 'brief_hash' => $intake_unknown_pipeline['brief']['hash'] ?? '', 'plan_hash' => $intake_unknown_pipeline['plan']['brief_hash'] ?? '' ], JSON_UNESCAPED_UNICODE ) );
$intake_unknown_failure = $run_services_route( $intake_unknown_prompt, [ provider_reply( 'not JSON' ), provider_reply( wp_json_encode( $intake_unknown_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-classified-freeform-no-retry-without-frozen-family' );
$intake_unknown_failure_trace = (array) ( $intake_unknown_failure['error']['data']['intake'] ?? [] );
check( ! empty( $intake_unknown_failure['error'] ) && $intake_unknown_failure['calls'] === 1 && $intake_unknown_failure['writes'] === 0 && ( $intake_unknown_failure_trace['retry_suppressed_reason'] ?? '' ) === 'family_not_frozen' && $intake_unknown_failure['page_data'] === $legacy_page, 'A malformed freeform classification is not retried while family, slots, and facts remain provider-selected' );

$intake_hero_strings = $intake_collect_strings( [ $intake_hero['written'] ] );
check( in_array( 'Архитектура для жизни и встреч', $intake_hero_strings, true ) && in_array( 'Проектируем частные дома и общественные пространства с вниманием к задачам места и повседневному использованию.', $intake_hero_strings, true ) && in_array( '#contact', $intake_hero_strings, true ) && ! in_array( 'https://images.unsplash.com/photo-m1-fixture?wpae=1200x800', $intake_hero_strings, true ), 'Generated Hero native readback keeps model copy and exact CTA, with no forbidden photo' );

// Prove the server-generated fields use null source spans plus an authenticated
// provider provenance record; user-supplied copy remains source-spanned.
$intake_previous_options = $GLOBALS['options'][WPAE_LLM_SETTINGS_OPTION] ?? null;
$GLOBALS['options'][WPAE_LLM_SETTINGS_OPTION] = [ 'provider' => 'openrouter', 'model' => 'openrouter/free', 'design_pipeline_mode' => 'active', 'design_engine_mode' => 'active' ];
$GLOBALS['http_calls'] = [];
$intake_direct_provider_reply = provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) );
$intake_direct_provider_body = json_decode( $intake_direct_provider_reply['body'], true );
$intake_direct_provider_body['model'] = 'example/free-endpoint-2026-10';
$intake_direct_provider_body['provider_name'] = 'Example Endpoint';
$intake_direct_provider_body['usage'] = [ 'prompt_tokens' => 712, 'completion_tokens' => 96, 'total_tokens' => 808, 'completion_tokens_details' => [ 'reasoning_tokens' => 24 ] ];
$intake_direct_provider_reply['body'] = wp_json_encode( $intake_direct_provider_body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
$GLOBALS['responses'] = [ $intake_direct_provider_reply ];
$intake_direct = wpae_brief_ir_intake_extract( $intake_hero_prompt, wpae_brief_ir_parse( $intake_hero_prompt ), [ 'provider' => 'openrouter', 'model' => 'openrouter/free', 'base_url' => 'https://openrouter.ai/api/v1', 'api_key' => 'test-key' ] );
$intake_hero_copy_slots = wpae_brief_ir_generated_copy_slots( wpae_brief_ir_parse( $intake_hero_prompt ), $intake_hero_prompt );
$intake_old_hero_copy = [ 'intent' => [ 'archetype' => 'hero' ], 'content' => [ [ 'role' => 'title', 'copy_status' => 'generated', 'exact_text' => 'Архитектурная студия: жилые и общественные пространства' ] ] ];
check( ( $intake_hero_copy_slots[0]['max_words'] ?? 0 ) === 5 && ( $intake_hero_copy_slots[0]['max_chars'] ?? 0 ) === 44 && ! empty( $intake_hero_copy_slots[1]['distinct_from_generated_title'] ) && wpae_brief_ir_generated_text_overlaps_generated_title( 'Небольшая студия проектирует жилые и общественные пространства.', $intake_old_hero_copy ) && ! wpae_brief_ir_generated_text_overlaps_generated_title( 'Небольшая студия проектирует такие пространства с учётом особенностей места.', $intake_old_hero_copy ), 'Generated Hero headings receive a short reading-measure limit and shared-title/body overlap guard rejects the observed v316 repetition pattern' );
$intake_generated_items = array_values( array_filter( (array) ( $intake_direct['brief']['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['copy_status'] ?? '' ) === 'generated' ) );
check( ! empty( $intake_direct['ok'] ) && count( $intake_generated_items ) === 2 && count( array_filter( $intake_generated_items, static fn( $item ): bool => array_key_exists( 'source_span', $item ) && $item['source_span'] === null && wpae_brief_ir_generated_content_valid( $item, $intake_direct['brief'] ) ) ) === 2, 'Generated copy has null source spans and validates only with the server HMAC provenance: ' . wp_json_encode( [ 'ok' => $intake_direct['ok'] ?? false, 'error' => $intake_direct['error'] ?? '', 'intake' => $intake_direct['brief']['intake'] ?? [], 'items' => $intake_generated_items, 'valid' => array_map( static fn( $item ): bool => wpae_brief_ir_generated_content_valid( $item, $intake_direct['brief'] ), $intake_generated_items ) ], JSON_UNESCAPED_UNICODE ) );
check( ( $intake_direct['telemetry']['requested_model'] ?? '' ) === 'openrouter/free' && ( $intake_direct['telemetry']['returned_model'] ?? '' ) === 'example/free-endpoint-2026-10' && ( $intake_direct['telemetry']['attempts'][0]['endpoint_provider'] ?? '' ) === 'Example Endpoint' && ( $intake_direct['telemetry']['usage']['input_tokens'] ?? null ) === 712 && ( $intake_direct['telemetry']['usage']['reasoning_tokens'] ?? null ) === 24 && ( $intake_direct['telemetry']['attempts'][0]['write_count'] ?? null ) === 0, 'Safe attempt telemetry distinguishes router from returned model and records known token/reasoning counters without claiming writes' );
check( ( $intake_direct['telemetry']['semantic_validation_result'] ?? '' ) === 'accepted' && ( $intake_direct['telemetry']['attempts'][0]['schema_validation_result'] ?? '' ) === 'accepted' && ( $intake_direct['telemetry']['attempts'][0]['schema_sha256'] ?? '' ) === $intake_direct['telemetry']['schema_sha256'] && ( $intake_direct['telemetry']['attempts'][0]['prompt_bytes'] ?? 0 ) > 0, 'Accepted attempt reports the same schema hash and bounded prompt diagnostics without exposing generated text' );
$intake_legacy_signed_items = array_map( static function ( array $item ) use ( $intake_direct ): array {
	unset( $item['provenance']['generation']['paragraph_count'], $item['provenance']['generation']['signature'] );
	$item['provenance']['generation']['signature'] = hash_hmac( 'sha256', wpae_brief_ir_generated_copy_signature_payload( $item, $intake_direct['brief'] ), (string) wp_salt( 'auth' ) );
	return $item;
}, $intake_generated_items );
check( count( $intake_legacy_signed_items ) === 2 && count( array_filter( $intake_legacy_signed_items, static fn( $item ): bool => wpae_brief_ir_generated_content_valid( $item, $intake_direct['brief'] ) ) ) === 2, 'v315-style generated Brief signatures remain valid when the optional paragraph-count extension is absent' );
$intake_v1_signed_items = array_map( static function ( array $item ) use ( $intake_direct ): array {
	$item['provenance']['generation']['schema'] = 'wpae-generated-copy-v1';
	unset( $item['provenance']['generation']['signature'] );
	$item['provenance']['generation']['signature'] = hash_hmac( 'sha256', wpae_brief_ir_generated_copy_signature_payload( $item, $intake_direct['brief'] ), (string) wp_salt( 'auth' ) );
	return $item;
}, $intake_generated_items );
check( count( $intake_v1_signed_items ) === 2 && count( array_filter( $intake_v1_signed_items, static fn( $item ): bool => wpae_brief_ir_generated_content_valid( $item, $intake_direct['brief'] ) ) ) === 2, 'Historical v1 generated-copy provenance remains valid beside the new claim-guarded v2 schema' );
check( ( $GLOBALS['http_calls'][0]['body']['max_tokens'] ?? 0 ) === WPAE_BRIEF_IR_INTAKE_MAX_COMPLETION_TOKENS, 'Typed provider intake uses its shared bounded multilingual response budget' );
check( ( $GLOBALS['http_calls'][0]['body']['response_format']['type'] ?? '' ) === 'json_schema' && ! empty( $GLOBALS['http_calls'][0]['body']['response_format']['json_schema']['strict'] ) && ! empty( $GLOBALS['http_calls'][0]['body']['provider']['require_parameters'] ), 'Typed intake sends strict JSON Schema and OpenRouter require_parameters on the normalized wire request' );
$intake_wire_schema = (array) ( $GLOBALS['http_calls'][0]['body']['response_format']['json_schema']['schema'] ?? [] );
check( ( $intake_wire_schema['additionalProperties'] ?? null ) === false && in_array( 'family', (array) ( $intake_wire_schema['required'] ?? [] ), true ) && in_array( 'generated', (array) ( $intake_wire_schema['required'] ?? [] ), true ) && ( $intake_wire_schema['properties']['generated']['items']['anyOf'][0]['properties']['slot_id']['enum'] ?? [] ) === [ 'section_title' ], 'Wire schema closes top-level keys and constrains generated slot IDs to the authorized Brief slots' );
check( ( $intake_wire_schema['properties']['generated']['items']['anyOf'][0]['properties']['text']['maxLength'] ?? 0 ) === 44 && ! isset( $intake_wire_schema['anyOf'] ), 'Strict schema encodes the generated Hero title measure without adding a contradictory root anyOf' );
$intake_no_facts_schema = wpae_brief_ir_intake_response_schema( [ 'hero' ], [ [ 'slot_id' => 'section_title', 'role' => 'title' ] ], [] );
$intake_facts_schema = wpae_brief_ir_intake_response_schema( [ 'benefits' ], [ [ 'slot_id' => 'benefits_1_description', 'role' => 'feature_body', 'requires_fact_ref' => true ] ], [ 'fact_1', 'fact_2' ] );
check( ( $intake_facts_schema['properties']['generated']['items']['properties']['fact_refs']['items']['enum'] ?? [] ) === [ 'fact_1', 'fact_2' ] && ( $intake_facts_schema['properties']['generated']['items']['properties']['fact_refs']['maxItems'] ?? 0 ) === 2 && ( $intake_no_facts_schema['properties']['generated']['items']['properties']['fact_refs']['maxItems'] ?? -1 ) === 0, 'Each strict schema limits fact references to approved IDs and disallows them when the authorized fact set is empty' );
$retryable_probe = [ 'ok' => false, 'telemetry' => [ 'refusal' => 'malformed_json' ] ];
$deadline_retry_decision = wpae_brief_ir_intake_retry_decision( $retryable_probe, 999 );
$unfrozen_retry_decision = wpae_brief_ir_intake_retry_decision( $retryable_probe, 5000, false );
check( empty( $deadline_retry_decision['retry'] ) && ( $deadline_retry_decision['reason'] ?? '' ) === 'malformed_json' && ( $deadline_retry_decision['suppressed_reason'] ?? '' ) === 'deadline_exhausted' && empty( $unfrozen_retry_decision['retry'] ) && ( $unfrozen_retry_decision['suppressed_reason'] ?? '' ) === 'family_not_frozen', 'Retry is suppressed when the shared deadline is exhausted or a freeform family/slot context is not frozen' );
$compat_format_request = [ 'response_format' => [ 'type' => 'json_object' ] ];
$legacy_normalized_format = wpae_llm_prepare_provider_request_body( $compat_format_request, true, 'gemini' );
$typed_normalized_format = wpae_llm_prepare_provider_request_body( $compat_format_request, true, 'gemini', [ 'contract' => 'typed_intake_strict' ] );
check( ! isset( $legacy_normalized_format['response_format'] ) && ( $typed_normalized_format['response_format']['type'] ?? '' ) === 'json_object', 'Legacy Gemini action compatibility remains isolated while strict typed normalization preserves the caller response format' );
$transport_unknown_diagnostics = wpae_llm_build_request_diagnostics( 'https://example.test/v1/chat/completions', [ 'timeout' => 10 ], [ 'messages' => [] ], 'openrouter', 'openrouter/free', 'primary', true, 0, '', [] );
$transport_known_diagnostics = wpae_llm_build_request_diagnostics( 'https://example.test/v1/chat/completions', [ 'timeout' => 10 ], [ 'messages' => [] ], 'openrouter', 'openrouter/free', 'primary', true, 200, '{"choices":[{"finish_reason":"stop"}]}', [ 'choices' => [ [ 'finish_reason' => 'stop' ] ] ] );
check( array_key_exists( 'http_status', $transport_unknown_diagnostics['response'] ?? [] ) && $transport_unknown_diagnostics['response']['http_status'] === null && array_key_exists( 'finish_reason', $transport_unknown_diagnostics['response'] ?? [] ) && $transport_unknown_diagnostics['response']['finish_reason'] === null && wpae_llm_diagnostic_http_status( 0 ) === null, 'Provider diagnostics preserve unknown HTTP and finish status as null rather than reporting zero or an empty reason' );
check( ( $transport_known_diagnostics['response']['http_status'] ?? null ) === 200 && ( $transport_known_diagnostics['response']['finish_reason'] ?? '' ) === 'stop', 'Provider diagnostics retain observed HTTP status and finish reason' );
if ( $intake_previous_options === null ) { unset( $GLOBALS['options'][WPAE_LLM_SETTINGS_OPTION] ); } else { $GLOBALS['options'][WPAE_LLM_SETTINGS_OPTION] = $intake_previous_options; }

// A strict typed caller must refuse an unsupported endpoint without weakening
// response_format/provider requirements or falling through to legacy output.
$GLOBALS['responses'] = [
	[ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( [ 'error' => [ 'message' => 'No endpoints found' ] ] ) ],
	provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ),
];
$intake_transport_retry = $run_services_route( $intake_hero_prompt, $GLOBALS['responses'], [], 'intake-generated-hero-transport-retry' );
$intake_transport_trace = (array) ( $intake_transport_retry['error']['data']['intake'] ?? [] );
check( ! empty( $intake_transport_retry['error'] ) && $intake_transport_retry['calls'] === 1 && $intake_transport_retry['writes'] === 0 && ( $intake_transport_trace['provider_calls'] ?? 0 ) === 1 && ( $intake_transport_trace['retry_count'] ?? -1 ) === 0 && ( $intake_transport_trace['refusal'] ?? '' ) === 'no_compatible_structured_endpoint', 'No compatible structured endpoint is a diagnostic no-write refusal and never enters the legacy generator: ' . wp_json_encode( [ 'error' => $intake_transport_retry['error'], 'response' => $intake_transport_retry['response'], 'calls' => $intake_transport_retry['calls'], 'writes' => $intake_transport_retry['writes'] ], JSON_UNESCAPED_UNICODE ) );
check( ( $intake_transport_retry['http_calls'][0]['body']['response_format']['type'] ?? '' ) === 'json_schema' && ! empty( $intake_transport_retry['http_calls'][0]['body']['provider']['require_parameters'] ) && $intake_transport_retry['page_data'] === $legacy_page, 'Unsupported endpoint does not trigger a second request with downgraded typed requirements' );
$GLOBALS['http_calls'] = [];
$invalid_request_schema = $run_services_route( $intake_hero_prompt, [ [ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( [ 'error' => [ 'message' => 'Invalid JSON schema: unsupported keyword for this endpoint' ] ] ) ] ], [], 'intake-invalid-provider-schema' );
$invalid_request_trace = (array) ( $invalid_request_schema['error']['data']['intake'] ?? [] );
check( ! empty( $invalid_request_schema['error'] ) && $invalid_request_schema['calls'] === 1 && $invalid_request_schema['writes'] === 0 && ( $invalid_request_trace['refusal'] ?? '' ) === 'invalid_request_schema' && ( $invalid_request_trace['semantic_validation_result'] ?? '' ) === 'request_schema_rejected' && ( $invalid_request_trace['retry_count'] ?? -1 ) === 0 && ( $invalid_request_schema['http_calls'][0]['body']['response_format']['type'] ?? '' ) === 'json_schema' && ! empty( $invalid_request_schema['http_calls'][0]['body']['provider']['require_parameters'] ), 'Invalid request schema is a one-call no-write refusal with strict wire requirements intact' );

$GLOBALS['http_calls'] = [];
$typed_provider_error_body = [
    'model' => 'returned/openrouter-route',
    'provider' => 'AtlasCloud',
    'error' => [
        'code' => 400,
        'message' => 'Provider returned error',
        'metadata' => [
            'error_type' => 'invalid_request',
            'provider_code' => 'schema_keyword_not_supported',
            'provider_name' => 'AtlasCloud',
            'param' => 'response_format',
            'path' => 'response_format.json_schema.schema.properties.generated.items.anyOf',
            'raw' => wp_json_encode( [ 'error' => [ 'message' => 'Invalid JSON schema: unsupported keyword. Request: ' . $intake_hero_prompt . ' Authorization: Bearer fake-secret-value token=sk-or-v1-fake-secret-value', 'code' => 'schema_keyword_not_supported', 'type' => 'invalid_request', 'param' => 'response_format', 'path' => 'response_format.json_schema.schema.properties.generated.items.anyOf' ], 'private_blob' => 'RAW_UPSTREAM_SECRET_SHOULD_NOT_ESCAPE' ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ),
        ],
    ],
];
$typed_provider_error = $run_services_route( $intake_hero_prompt, [ [ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( $typed_provider_error_body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ] ], [], 'intake-provider-diagnostics-allowlist' );
$typed_provider_trace = (array) ( $typed_provider_error['error']['data']['intake'] ?? [] );
$typed_provider_attempt = (array) ( $typed_provider_trace['attempts'][0] ?? [] );
check( ! empty( $typed_provider_error['error'] ) && $typed_provider_error['calls'] === 1 && $typed_provider_error['writes'] === 0 && $typed_provider_error['page_data'] === $legacy_page && ( $typed_provider_trace['failure_class'] ?? '' ) === 'request_schema_rejected' && ! empty( $typed_provider_trace['provider_error_envelope'] ) && ! empty( $typed_provider_trace['http_failure'] ) && ( $typed_provider_trace['provider_error_class'] ?? '' ) === 'request_schema_rejected', 'A typed provider rejection remains a single no-write refusal with separate envelope and request-schema classifications' );
check( ( $typed_provider_attempt['http_status'] ?? null ) === 400 && ( $typed_provider_attempt['provider_error_code'] ?? '' ) === 'schema_keyword_not_supported' && ( $typed_provider_attempt['provider_error_type'] ?? '' ) === 'invalid_request' && ( $typed_provider_attempt['provider_error_param'] ?? '' ) === 'response_format' && strpos( (string) ( $typed_provider_attempt['provider_error_path'] ?? '' ), 'anyOf' ) !== false && ( $typed_provider_attempt['requested_model'] ?? '' ) === 'openrouter/free' && ( $typed_provider_attempt['returned_model'] ?? '' ) === 'returned/openrouter-route' && ( $typed_provider_attempt['provider_name'] ?? '' ) === 'AtlasCloud', 'Attempt diagnostics preserve safe provider error fields and distinguish disclosed model/provider from the API endpoint' );
check( ( $typed_provider_attempt['response_format'] ?? '' ) === 'json_schema' && ! empty( $typed_provider_attempt['response_format_strict'] ) && ! empty( $typed_provider_attempt['require_parameters'] ) && strlen( (string) ( $typed_provider_attempt['schema_sha256'] ?? '' ) ) === 64 && (int) ( $typed_provider_attempt['schema_bytes'] ?? 0 ) > 0 && strpos( (string) ( $typed_provider_attempt['api_endpoint'] ?? '' ), 'openrouter.ai/api/v1/chat/completions' ) !== false && ( $typed_provider_trace['provider_calls'] ?? 0 ) === 1 && ( $typed_provider_trace['actual_http_calls'] ?? 0 ) === 1 && ( $typed_provider_trace['retry_count'] ?? -1 ) === 0 && ( $typed_provider_trace['write_count'] ?? -1 ) === 0, 'Diagnostics record strict routing, schema fingerprint/size, sanitized API endpoint, real calls, retry, and write count' );
$typed_diagnostic_json = (string) wp_json_encode( $typed_provider_trace, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
check( strpos( $typed_diagnostic_json, 'RAW_UPSTREAM_SECRET_SHOULD_NOT_ESCAPE' ) === false && strpos( $typed_diagnostic_json, $intake_hero_prompt ) === false && strpos( $typed_diagnostic_json, 'fake-secret-value' ) === false && json_decode( $typed_diagnostic_json, true ) !== null, 'Diagnostic serialization excludes raw upstream metadata and reflected request text while preserving valid JSON' );

$GLOBALS['http_calls'] = [];
$unknown_provider_error = $run_services_route( $intake_hero_prompt, [ [ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( [ 'error' => [ 'code' => 400, 'metadata' => [ 'raw' => 'opaque raw body' ] ] ] ) ] ], [], 'intake-provider-diagnostics-unknown' );
$unknown_provider_trace = (array) ( $unknown_provider_error['error']['data']['intake'] ?? [] );
$unknown_provider_attempt = (array) ( $unknown_provider_trace['attempts'][0] ?? [] );
check( ! empty( $unknown_provider_error['error'] ) && $unknown_provider_error['calls'] === 1 && $unknown_provider_error['writes'] === 0 && ( $unknown_provider_trace['provider_error_class'] ?? '' ) === 'UNKNOWN' && ( $unknown_provider_attempt['provider_error_code'] ?? null ) === null && ( $unknown_provider_attempt['provider_error_type'] ?? null ) === null && ( $unknown_provider_attempt['provider_message'] ?? null ) === null, 'Missing upstream details remain UNKNOWN/null rather than inferred from HTTP 400 or raw metadata' );

$GLOBALS['http_calls'] = [];
$http_200_error_envelope = $run_services_route( $intake_hero_prompt, [ [ 'response' => [ 'code' => 200 ], 'body' => wp_json_encode( [ 'error' => [ 'code' => 429, 'message' => 'provider rate limit exceeded', 'metadata' => [ 'error_type' => 'rate_limit_exceeded' ] ], 'model' => 'returned/failed-route' ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ] ], [], 'intake-http-200-error-envelope' );
$http_200_error_trace = (array) ( $http_200_error_envelope['error']['data']['intake'] ?? [] );
check( ! empty( $http_200_error_envelope['error'] ) && $http_200_error_envelope['calls'] === 1 && $http_200_error_envelope['writes'] === 0 && $http_200_error_envelope['write_attempts'] === 0 && $http_200_error_envelope['page_data'] === $legacy_page && ( $http_200_error_trace['refusal'] ?? '' ) === 'provider_error_envelope' && ( $http_200_error_trace['failure_class'] ?? '' ) === 'upstream_error_envelope' && ( $http_200_error_trace['retry_count'] ?? -1 ) === 0, 'An HTTP 200 upstream error envelope is not parsed as model copy, retried as syntax failure, or written' );

$utf8_diagnostic_input = str_repeat( 'Ошибка схемы 😀 кириллица ', 80 );
$utf8_diagnostic = wpae_llm_diagnostic_text( $utf8_diagnostic_input, 301 );
$utf8_diagnostic_json = (string) wp_json_encode( [ 'message' => $utf8_diagnostic ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
$utf8_roundtrip = json_decode( $utf8_diagnostic_json, true );
check( strlen( $utf8_diagnostic ) <= 301 && preg_match( '//u', $utf8_diagnostic ) === 1 && is_array( $utf8_roundtrip ) && ( $utf8_roundtrip['message'] ?? '' ) === $utf8_diagnostic && strpos( $utf8_diagnostic, '😀' ) !== false, 'Diagnostics truncate UTF-8 on codepoint boundaries and round-trip Russian, emoji, and over-limit messages safely' );

$GLOBALS['http_calls'] = [];
$GLOBALS['responses'] = [ [ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( [ 'error' => [ 'message' => 'No endpoints found' ] ] ) ], provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ];
$intake_direct_retry = wpae_brief_ir_intake_extract( $intake_hero_prompt, wpae_brief_ir_parse( $intake_hero_prompt ), [ 'provider' => 'openrouter', 'model' => 'openrouter/free', 'base_url' => 'https://openrouter.ai/api/v1', 'api_key' => 'test-key' ] );
$intake_retry_items = array_values( array_filter( (array) ( $intake_direct_retry['brief']['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['copy_status'] ?? '' ) === 'generated' ) );
check( empty( $intake_direct_retry['ok'] ) && ( $intake_direct_retry['telemetry']['provider_calls'] ?? 0 ) === 1 && ( $intake_direct_retry['telemetry']['retry_count'] ?? -1 ) === 0 && ( $intake_direct_retry['telemetry']['refusal'] ?? '' ) === 'no_compatible_structured_endpoint' && $GLOBALS['http_calls'][0]['body']['response_format']['type'] === 'json_schema', 'Direct typed intake also refuses unsupported structured routing without a downgraded retry' );

$GLOBALS['http_calls'] = [];
$GLOBALS['responses'] = [
	[ 'response' => [ 'code' => 200 ], 'body' => wp_json_encode( [ 'choices' => [ [ 'finish_reason' => 'length', 'message' => [ 'content' => '{"family":"hero","generated":[' ] ] ] ] ) ],
	provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ),
];
$intake_length_retry = $run_services_route( $intake_hero_prompt, $GLOBALS['responses'], [], 'intake-generated-hero-length-retry' );
$intake_length_trace = (array) ( $intake_length_retry['response']['diagnostics']['intake'] ?? [] );
check( ! empty( $intake_length_retry['response']['ok'] ) && $intake_length_retry['calls'] === 2 && $intake_length_retry['writes'] === 1 && ( $intake_length_trace['retry_reason'] ?? '' ) === 'finish_reason_length' && ( $intake_length_trace['first_finish_reason'] ?? '' ) === 'length' && ( $intake_length_trace['finish_reason'] ?? '' ) === 'stop' && count( (array) ( $intake_length_trace['attempts'] ?? [] ) ) === 2, 'A length-truncated typed response receives one bounded schema-preserving retry and exposes both attempts' );
check( count( array_filter( $intake_length_retry['http_calls'], static fn( $call ): bool => ( $call['body']['response_format']['type'] ?? '' ) === 'json_schema' && ! empty( $call['body']['response_format']['json_schema']['strict'] ) && ! empty( $call['body']['provider']['require_parameters'] ) ) ) === 2 && $intake_length_retry['http_calls'][0]['body']['response_format']['json_schema']['schema'] === $intake_length_retry['http_calls'][1]['body']['response_format']['json_schema']['schema'], 'Length retry keeps the exact same strict schema, family, fact set and provider requirement on both wire attempts' );

$GLOBALS['http_calls'] = [];
$GLOBALS['responses'] = [ provider_reply( 'not JSON' ), provider_reply( wp_json_encode( $intake_hero_response, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ];
$intake_malformed_retry = $run_services_route( $intake_hero_prompt, $GLOBALS['responses'], [], 'intake-malformed-json-retry' );
$intake_malformed_trace = (array) ( $intake_malformed_retry['response']['diagnostics']['intake'] ?? [] );
check( ! empty( $intake_malformed_retry['response']['ok'] ) && $intake_malformed_retry['calls'] === 2 && $intake_malformed_retry['writes'] === 1 && ( $intake_malformed_trace['retry_reason'] ?? '' ) === 'malformed_json' && count( (array) ( $intake_malformed_trace['attempts'] ?? [] ) ) === 2, 'Malformed JSON at finish_reason=stop gets one syntax-only retry, then one frozen Brief and transaction' );
check( count( array_filter( $intake_malformed_retry['http_calls'], static fn( $call ): bool => ( $call['body']['response_format']['type'] ?? '' ) === 'json_schema' && ! empty( $call['body']['provider']['require_parameters'] ) ) ) === 2, 'Syntax retry never removes the strict schema or endpoint capability requirement' );

$GLOBALS['http_calls'] = [];
$GLOBALS['responses'] = [ [ 'response' => [ 'code' => 400 ], 'body' => wp_json_encode( [ 'error' => [ 'message' => 'No endpoints found' ] ] ) ] ];
$GLOBALS['provider_sleep_usec'] = 200000;
$expired_retry_attempts = [];
$expired_retry = wpae_llm_provider_request( 'https://openrouter.ai/api/v1/chat/completions', [ 'timeout' => 5, 'body' => '{}' ], [ 'model' => 'openrouter/free', 'messages' => [] ], true, 'openrouter', microtime( true ) + 1.05, $expired_retry_attempts );
unset( $GLOBALS['provider_sleep_usec'] );
check( is_wp_error( $expired_retry ) && $expired_retry->get_error_code() === 'wpae_llm_provider_budget_exhausted' && count( $GLOBALS['http_calls'] ) === 1 && ( $expired_retry_attempts['provider_calls'] ?? 0 ) === 1 && ( $expired_retry_attempts['retry_count'] ?? -1 ) === 0, 'Expired shared deadline refuses the schema retry without claiming an unmade provider attempt' );

$intake_about_prompt = "Создай блок О нас с фото из разрешённых материалов. Заголовок: «Студия, которая слушает место».\nФакты: учитываем рельеф участка; согласуем планировку до разработки чертежей.\nСформулируй два коротких абзаца только на основе этих фактов.";
$intake_about_probe = wpae_brief_ir_parse( $intake_about_prompt );
$intake_about_slots = wpae_brief_ir_generated_copy_slots( $intake_about_probe, $intake_about_prompt );
$intake_about_facts = wpae_brief_ir_approved_facts( $intake_about_probe, $intake_about_prompt );
$intake_about_schema = wpae_brief_ir_intake_response_schema( [ 'about' ], $intake_about_slots, array_column( $intake_about_facts, 'id' ) );
$intake_about_item_schema = (array) ( $intake_about_schema['properties']['generated']['items'] ?? [] );
check( ( $intake_about_item_schema['properties']['paragraphs']['minItems'] ?? 0 ) === 2 && ( $intake_about_item_schema['properties']['paragraphs']['maxItems'] ?? 0 ) === 2 && ! isset( $intake_about_item_schema['properties']['text'] ) && ( $intake_about_item_schema['properties']['fact_refs']['items']['enum'] ?? [] ) === array_column( $intake_about_facts, 'id' ) && ( $intake_about_item_schema['additionalProperties'] ?? null ) === false, 'Paragraph slots use paragraph-only schema with exact count, authorized fact IDs, and no unexpected keys' );
$intake_about_payload = [ 'family' => 'about', 'generated' => [ [ 'slot_id' => 'section_intro', 'paragraphs' => [ 'Учитываем рельеф участка при выборе проектных решений.', 'Планировку согласуем до перехода к чертежам.' ], 'fact_refs' => array_column( $intake_about_facts, 'id' ) ] ] ];
$intake_about_media = array_replace( $m1_media, [ 'role' => 'about', 'group_id' => 'about', 'alt' => 'Современный интерьер архитектурной студии.' ] );
$intake_about = $run_services_route( $intake_about_prompt, [ provider_reply( wp_json_encode( $intake_about_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-hybrid-about', false, 'active', 'active', [ 'media_references' => [ $intake_about_media ] ] );
$intake_about_pipeline = (array) ( $intake_about['response']['diagnostics']['design_pipeline'] ?? [] );
$intake_about_strings = $intake_collect_strings( [ $intake_about['written'] ] );
$intake_about_strings = array_map( static fn( string $value ): string => preg_replace( "/\\n{2,}/", "\n", $value ), $intake_about_strings );
check( array_column( $intake_about_slots, 'slot_id' ) === [ 'section_intro' ] && ( $intake_about_slots[0]['paragraph_count'] ?? 0 ) === 2 && count( $intake_about_facts ) >= 2 && ! empty( $intake_about['response']['ok'] ) && $intake_about['calls'] === 1 && $intake_about['writes'] === 1, 'Hybrid About ordinary chat locks its exact title and makes the provider return exactly two authorized body paragraphs: ' . wp_json_encode( [ 'slots' => $intake_about_slots, 'facts' => $intake_about_facts, 'error' => $intake_about['error'] ], JSON_UNESCAPED_UNICODE ) );
check( in_array( 'Студия, которая слушает место', $intake_about_strings, true ) && in_array( "Учитываем рельеф участка при выборе проектных решений.\nПланировку согласуем до перехода к чертежам.", $intake_about_strings, true ) && ( $intake_about_pipeline['brief']['hash'] ?? '' ) === ( $intake_about_pipeline['plan']['brief_hash'] ?? '' ), 'Hybrid About preserves exact title and ordered generated paragraph copy in native readback while the Plan uses one frozen Brief hash' );
$intake_about_media_context = [ 'media_references' => [ $intake_about_media ] ];
$intake_about_collapsed_payload = provider_reply( wp_json_encode( [ 'family' => 'about', 'generated' => [ [ 'slot_id' => 'section_intro', 'text' => 'Учитываем рельеф участка и согласуем планировку до чертежей.', 'fact_refs' => array_column( $intake_about_facts, 'id' ) ] ] ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) );
$intake_about_one_paragraph = $run_services_route( $intake_about_prompt, [ $intake_about_collapsed_payload, $intake_about_collapsed_payload ], [], 'intake-about-paragraph-collapse', false, 'active', 'active', $intake_about_media_context );
$intake_about_wrong_count_payload = provider_reply( wp_json_encode( [ 'family' => 'about', 'generated' => [ [ 'slot_id' => 'section_intro', 'paragraphs' => [ 'Учитываем рельеф участка при выборе проектных решений.' ], 'fact_refs' => array_column( $intake_about_facts, 'id' ) ] ] ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) );
$intake_about_wrong_count = $run_services_route( $intake_about_prompt, [ $intake_about_wrong_count_payload, $intake_about_wrong_count_payload ], [], 'intake-about-wrong-paragraph-count', false, 'active', 'active', $intake_about_media_context );
$intake_about_repeated_title = $run_services_route( $intake_about_prompt, [ provider_reply( wp_json_encode( [ 'family' => 'about', 'generated' => [ [ 'slot_id' => 'section_intro', 'paragraphs' => [ 'Студия, которая слушает место. На первой встрече обсуждаем пожелания и ограничения пространства.', 'Планировку согласуем до разработки чертежей.' ], 'fact_refs' => array_column( $intake_about_facts, 'id' ) ] ] ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-about-repeated-exact-heading', false, 'active', 'active', $intake_about_media_context );
check( ( $intake_about_one_paragraph['error']['code'] ?? '' ) === 'intake_paragraph_count_invalid' && $intake_about_one_paragraph['calls'] === 2 && ( $intake_about_one_paragraph['error']['data']['intake']['retry_count'] ?? 0 ) === 1 && $intake_about_one_paragraph['writes'] === 0 && $intake_about_one_paragraph['write_attempts'] === 0 && $intake_about_one_paragraph['page_data'] === $legacy_page, 'A provider that collapses a two-paragraph slot twice is refused after one schema-only retry and before transaction: ' . wp_json_encode( [ 'error' => $intake_about_one_paragraph['error'], 'calls' => $intake_about_one_paragraph['calls'], 'writes' => $intake_about_one_paragraph['writes'], 'write_attempts' => $intake_about_one_paragraph['write_attempts'] ], JSON_UNESCAPED_UNICODE ) );
check( ( $intake_about_wrong_count['error']['code'] ?? '' ) === 'intake_paragraph_count_invalid' && $intake_about_wrong_count['calls'] === 2 && $intake_about_wrong_count['writes'] === 0 && $intake_about_wrong_count['page_data'] === $legacy_page, 'A generated paragraph array with the wrong cardinality remains a no-write refusal after its only bounded retry' );
check( ( $intake_about_repeated_title['error']['code'] ?? '' ) === 'intake_generated_heading_repeated' && $intake_about_repeated_title['writes'] === 0 && $intake_about_repeated_title['page_data'] === $legacy_page, 'Generated About body cannot repeat its exact author-provided heading: ' . wp_json_encode( [ 'error' => $intake_about_repeated_title['error'], 'calls' => $intake_about_repeated_title['calls'], 'writes' => $intake_about_repeated_title['writes'] ], JSON_UNESCAPED_UNICODE ) );

$intake_about_directive_prompt = 'Создай новую редакционную секцию About. Заголовок должен быть ровно таким и не изменяться: «Проект начинается с диалога о привычках». Используй изображение https://images.unsplash.com/photo-1766230976347-c5badd3f76c9?auto=format&fit=crop&fm=jpg&h=675&ixlib=rb-4.1.0&q=80&w=1200 . Alt должен быть точным: «Современный архитектурный интерьер с панорамным светом.» Лицензия: Unsplash License. Сформулируй два коротких абзаца только из разрешённых фактов.';
$intake_about_directive_brief = wpae_brief_ir_parse( $intake_about_directive_prompt );
$intake_about_directive_slots = wpae_brief_ir_generated_copy_slots( $intake_about_directive_brief, $intake_about_directive_prompt );
$intake_about_directive_title = array_values( array_filter( (array) ( $intake_about_directive_brief['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['role'] ?? '' ) === 'title' ) );
$intake_about_directive_alt = (string) ( $intake_about_directive_brief['media_references'][0]['alt'] ?? '' );
$intake_about_directive_alt_as_copy = array_filter( (array) ( $intake_about_directive_brief['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['exact_text'] ?? '' ) === 'Современный архитектурный интерьер с панорамным светом.' );
check( ( $intake_about_directive_brief['intent']['archetype'] ?? '' ) === 'about' && ( $intake_about_directive_title[0]['exact_text'] ?? '' ) === 'Проект начинается с диалога о привычках' && array_column( $intake_about_directive_slots, 'slot_id' ) === [ 'section_intro' ] && $intake_about_directive_alt === 'Современный архитектурный интерьер с панорамным светом.' && empty( $intake_about_directive_alt_as_copy ), 'About directive language keeps exact title in its typed slot and alt metadata out of authored copy; intake generates only the authorized intro: ' . wp_json_encode( [ 'family' => $intake_about_directive_brief['intent']['archetype'] ?? '', 'content' => $intake_about_directive_brief['content'] ?? [], 'slots' => $intake_about_directive_slots, 'alt' => $intake_about_directive_alt, 'asset' => $intake_about_directive_brief['media_references'][0] ?? [] ], JSON_UNESCAPED_UNICODE ) );

$intake_ordered_benefits_prompt = 'Создай секцию Benefits с тремя преимуществами. Заголовки и их порядок сохрани точно: «Сценарии до деталей»; «Целостность решений»; «Документация для реализации». Напиши по одному короткому пояснению для каждой темы, используя только эти факты: на первой встрече собирают пожелания и ограничения помещения; планировочные варианты сравнивают по дневному свету, маршрутам движения и хранению; после выбора направления согласуют материалы, инженерные решения и документацию; решения и открытые вопросы фиксируют для дальнейшего обсуждения. Пояснения сгенерируй моделью, сохрани связь каждого описания с соответствующим заголовком. Не добавляй цифры, сроки, опыт, клиентов, награды, гарантии, обещания, CTA, фотографии или другие изображения. Композиция — автоматически. Добавь секцию к существующей странице.';
$intake_ordered_benefits_brief = wpae_brief_ir_parse( $intake_ordered_benefits_prompt );
$intake_ordered_benefits_titles = array_values( array_filter( (array) ( $intake_ordered_benefits_brief['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['role'] ?? '' ) === 'feature_title' ) );
$intake_ordered_benefits_slots = wpae_brief_ir_generated_copy_slots( $intake_ordered_benefits_brief, $intake_ordered_benefits_prompt );
$intake_ordered_benefits_spans = array_reduce( $intake_ordered_benefits_titles, static fn( bool $valid, array $item ): bool => $valid && substr( $intake_ordered_benefits_prompt, (int) $item['source_span'][0], (int) $item['source_span'][1] - (int) $item['source_span'][0] ) === (string) $item['exact_text'], true );
check( ( $intake_ordered_benefits_brief['intent']['archetype'] ?? '' ) === 'benefits' && array_column( $intake_ordered_benefits_titles, 'exact_text' ) === [ 'Сценарии до деталей', 'Целостность решений', 'Документация для реализации' ] && array_column( $intake_ordered_benefits_titles, 'group_id' ) === [ 'benefits_1', 'benefits_2', 'benefits_3' ] && $intake_ordered_benefits_spans && array_column( $intake_ordered_benefits_slots, 'slot_id' ) === [ 'benefits_1_description', 'benefits_2_description', 'benefits_3_description' ] && empty( $intake_ordered_benefits_brief['media_references'] ), 'Benefits keeps ordered quoted headings as exact grouped entities and exposes only three generated copy slots' );
$intake_inline_benefit_facts = wpae_brief_ir_approved_facts( $intake_ordered_benefits_brief, $intake_ordered_benefits_prompt );
$intake_inline_benefit_labeled_facts = array_values( array_filter( $intake_inline_benefit_facts, static fn( array $fact ): bool => ( $fact['provenance']['label'] ?? '' ) === 'labeled_fact' ) );
$intake_inline_benefit_fact_spans = array_reduce( $intake_inline_benefit_facts, static fn( bool $valid, array $fact ): bool => $valid && substr( $intake_ordered_benefits_prompt, (int) $fact['source_span'][0], (int) $fact['source_span'][1] - (int) $fact['source_span'][0] ) === (string) $fact['exact_text'], true );
check( array_column( $intake_inline_benefit_labeled_facts, 'exact_text' ) === [ 'на первой встрече собирают пожелания и ограничения помещения', 'планировочные варианты сравнивают по дневному свету, маршрутам движения и хранению', 'после выбора направления согласуют материалы, инженерные решения и документацию', 'решения и открытые вопросы фиксируют для дальнейшего обсуждения' ] && $intake_inline_benefit_fact_spans && empty( array_filter( $intake_inline_benefit_facts, static fn( array $fact ): bool => str_contains( $fact['exact_text'], 'Пояснения сгенерируй' ) || str_contains( $fact['exact_text'], 'Не добавляй' ) ) ), 'Inline Benefits facts: ' . wp_json_encode( [ 'facts' => $intake_inline_benefit_facts, 'spans_valid' => $intake_inline_benefit_fact_spans ], JSON_UNESCAPED_UNICODE ) );

$intake_inline_faq_prompt = 'Создай FAQ в виде настоящего native Elementor Accordion с тремя вопросами в указанном порядке. Вопросы сохрани точно. Сгенерируй ответы только на основе фактов сразу под соответствующим вопросом; не добавляй сроки, цены, гарантии, обязательства или дополнительные условия. Первый ответ должен быть коротким, третий — длинным, но полностью подтверждённым указанными фактами.' . "\n\n" . 'Вопрос 1: «Что обсуждается на первой встрече?» Факты: собирают пожелания и ограничения помещения.' . "\n" . 'Вопрос 2: «Как сравниваются планировочные варианты?» Факты: сравнивают дневной свет, маршруты движения и хранение.' . "\n" . 'Вопрос 3: «Что происходит после выбора планировочного направления?» Факты: согласуют материалы, инженерные решения и документацию; решения и открытые вопросы фиксируют для дальнейшего обсуждения.' . "\n\n" . 'Сохрани точные пары вопрос/ответ и порядок, не добавляй новые вопросы и визуальные карточки вместо Accordion. После создания проверь каждый ответ штатным раскрытием. Композиция — автоматически. Добавь FAQ к существующей странице.';
$intake_inline_faq_brief = wpae_brief_ir_parse( $intake_inline_faq_prompt );
$intake_inline_faq_facts = wpae_brief_ir_approved_facts( $intake_inline_faq_brief, $intake_inline_faq_prompt );
$intake_inline_faq_fact_spans = array_reduce( $intake_inline_faq_facts, static fn( bool $valid, array $fact ): bool => $valid && substr( $intake_inline_faq_prompt, (int) $fact['source_span'][0], (int) $fact['source_span'][1] - (int) $fact['source_span'][0] ) === (string) $fact['exact_text'], true );
check( ( $intake_inline_faq_brief['intent']['archetype'] ?? '' ) === 'faq' && array_column( $intake_inline_faq_facts, 'exact_text' ) === [ 'собирают пожелания и ограничения помещения', 'сравнивают дневной свет, маршруты движения и хранение', 'согласуют материалы, инженерные решения и документацию', 'решения и открытые вопросы фиксируют для дальнейшего обсуждения' ] && $intake_inline_faq_fact_spans, 'Inline FAQ fact labels after exact questions are approved with source spans and group question text is not treated as a fact' );

$intake_benefits_prompt = "Создай Benefits. Напиши описания к этим точным темам; не добавляй фото, CTA или числовые обещания.\nПреимущество 1: «Планировка под привычки»\nПреимущество 2: «Материалы местного производства»\nПреимущество 3: «Работа с рельефом»";
$intake_benefits_probe = wpae_brief_ir_parse( $intake_benefits_prompt );
$intake_benefits_slots = wpae_brief_ir_generated_copy_slots( $intake_benefits_probe, $intake_benefits_prompt );
$intake_benefits_facts = wpae_brief_ir_approved_facts( $intake_benefits_probe, $intake_benefits_prompt );
$intake_benefits_payload = [ 'family' => 'benefits', 'generated' => [] ];
$intake_benefit_copy = [ 'benefits_1_description' => 'Сверяем планировочные решения с привычками, названными в задании.', 'benefits_2_description' => 'Подбираем местные материалы в соответствии с замыслом проекта.', 'benefits_3_description' => 'Учитываем рельеф участка при разработке пространственных решений.' ];
foreach ( $intake_benefits_slots as $index => $slot ) { $intake_benefits_payload['generated'][] = [ 'slot_id' => $slot['slot_id'], 'text' => $intake_benefit_copy[ $slot['slot_id'] ] ?? '', 'fact_refs' => [ (string) ( $intake_benefits_facts[ $index ]['id'] ?? '' ) ] ]; }
$intake_benefits = $run_services_route( $intake_benefits_prompt, [ provider_reply( wp_json_encode( $intake_benefits_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-generated-benefits' );
$intake_benefits_strings = $intake_collect_strings( [ $intake_benefits['written'] ] );
check( array_column( $intake_benefits_slots, 'slot_id' ) === [ 'benefits_1_description', 'benefits_2_description', 'benefits_3_description' ] && ! empty( $intake_benefits['response']['ok'] ) && $intake_benefits['calls'] === 1 && $intake_benefits['writes'] === 1, 'Benefits ordinary chat generates one description for each of three stable groups' );
check( count( array_intersect( [ 'Планировка под привычки', 'Материалы местного производства', 'Работа с рельефом' ], $intake_benefits_strings ) ) === 3 && count( array_intersect( array_values( $intake_benefit_copy ), $intake_benefits_strings ) ) === 3 && ! in_array( 'https://images.unsplash.com/photo-m1-fixture?wpae=1200x800', $intake_benefits_strings, true ) && ( $intake_benefits['response']['diagnostics']['design_pipeline']['brief']['hash'] ?? '' ) === ( $intake_benefits['response']['diagnostics']['design_pipeline']['plan']['brief_hash'] ?? '' ), 'Benefits readback keeps title/body pairs, no added media, and the same frozen Brief hash' );

$intake_live_benefits_prompt = 'Создай блок Benefits с тремя пунктами. Используй эти точные заголовки и сохрани их порядок: «Планировка под повседневные сценарии»; «Работа с дневным светом»; «Продуманное хранение». Для каждого заголовка напиши одно короткое пояснение на основе только смысла самой темы; не добавляй цифры, сроки, гарантии, клиентов, результаты или другие бизнес-факты. Не меняй заголовки. Без фотографий, CTA, дополнительных пунктов и метрик. Композицию выбери автоматически. Добавь блок к существующей странице.';
$intake_live_benefits_probe = wpae_brief_ir_parse( $intake_live_benefits_prompt );
$intake_live_benefits_titles = array_values( array_filter( (array) ( $intake_live_benefits_probe['content'] ?? [] ), static fn( $item ): bool => is_array( $item ) && ( $item['role'] ?? '' ) === 'feature_title' ) );
$intake_live_benefits_slots = wpae_brief_ir_generated_copy_slots( $intake_live_benefits_probe, $intake_live_benefits_prompt );
$intake_live_benefits_facts = wpae_brief_ir_approved_facts( $intake_live_benefits_probe, $intake_live_benefits_prompt );
$intake_live_benefits_copy = [ 'benefits_1_description' => 'Учитываем привычные действия при организации планировки.', 'benefits_2_description' => 'Рассматриваем дневной свет как часть восприятия пространства.', 'benefits_3_description' => 'Предусматриваем хранение в общей организации интерьера.' ];
$intake_live_benefits_payload = [ 'family' => 'benefits', 'generated' => [] ];
foreach ( $intake_live_benefits_slots as $index => $slot ) {
	$intake_live_benefits_payload['generated'][] = [ 'slot_id' => $slot['slot_id'], 'text' => $intake_live_benefits_copy[ $slot['slot_id'] ] ?? '', 'fact_refs' => [ (string) ( $intake_live_benefits_facts[ $index ]['id'] ?? '' ) ] ];
}
$intake_live_benefits = $run_services_route( $intake_live_benefits_prompt, [ provider_reply( wp_json_encode( $intake_live_benefits_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-generated-benefits-ordered-quoted-headings' );
$intake_live_benefits_strings = $intake_collect_strings( [ $intake_live_benefits['written'] ] );
$intake_live_benefits_pipeline = (array) ( $intake_live_benefits['response']['diagnostics']['design_pipeline'] ?? [] );
$intake_live_benefits_system_prompt = (string) ( $intake_live_benefits['http_calls'][0]['body']['messages'][0]['content'] ?? '' );
check( array_column( $intake_live_benefits_titles, 'exact_text' ) === [ 'Планировка под повседневные сценарии', 'Работа с дневным светом', 'Продуманное хранение' ] && array_column( $intake_live_benefits_titles, 'group_id' ) === [ 'benefits_1', 'benefits_2', 'benefits_3' ] && array_column( $intake_live_benefits_slots, 'slot_id' ) === [ 'benefits_1_description', 'benefits_2_description', 'benefits_3_description' ], 'Benefits maps declared ordered headings to exact entity groups and authorized copy slots' );
check( array_reduce( $intake_live_benefits_titles, static fn( bool $valid, array $item ): bool => $valid && substr( $intake_live_benefits_prompt, (int) $item['source_span'][0], (int) $item['source_span'][1] - (int) $item['source_span'][0] ) === (string) $item['exact_text'], true ) && ! empty( $intake_live_benefits['response']['ok'] ) && $intake_live_benefits['calls'] === 1 && $intake_live_benefits['writes'] === 1 && ( $intake_live_benefits_pipeline['brief']['hash'] ?? '' ) === ( $intake_live_benefits_pipeline['plan']['brief_hash'] ?? '' ), 'Benefits ordinary chat preserves source spans and freezes one Brief before its single transaction' );
check( count( array_intersect( array_values( $intake_live_benefits_copy ), $intake_live_benefits_strings ) ) === 3 && ! array_filter( $intake_live_benefits_strings, static fn( string $text ): bool => str_contains( $text, 'images.unsplash.com' ) || str_contains( $text, '#contact' ) ), 'Benefits generated body text does not add media or CTA when forbidden' );
check( str_contains( $intake_live_benefits_system_prompt, 'slot_id is a required schema field' ) && str_contains( $intake_live_benefits_system_prompt, 'sole exception to the prohibition on IDs' ) && str_contains( $intake_live_benefits_system_prompt, 'Elementor element IDs' ), 'Typed intake prompt explicitly distinguishes required Brief slot IDs from forbidden Elementor element IDs' );

$intake_pricing_prompt = "Создай Pricing. Напиши только заголовок раздела и вступление; тарифные факты не меняй.\n«Старт» — «50 000 ₸/мес» — «Малый проект»\nFeatures: «Аудит», «План»\nКнопка: «Выбрать Старт», ссылка #start\n«Проект» — «150 000 ₸/год» — «Полный проект»\nFeatures: «Дизайн», «Разработка»\nКнопка: «Выбрать Проект», ссылка #project\n«Сопровождение» — «210 000 ₸/год» — «Контроль реализации»\nFeatures: «Выезды», «Отчёт»\nКнопка: «Выбрать Сопровождение», ссылка #support";
$intake_pricing_probe = wpae_brief_ir_parse( $intake_pricing_prompt );
$intake_pricing_slots = wpae_brief_ir_generated_copy_slots( $intake_pricing_probe, $intake_pricing_prompt );
$intake_pricing_payload = [ 'family' => 'pricing', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Тарифы на архитектурный проект', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Выберите состав работы, который подходит задаче вашего проекта.', 'fact_refs' => [] ] ] ];
$intake_pricing = $run_services_route( $intake_pricing_prompt, [ provider_reply( wp_json_encode( $intake_pricing_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-hybrid-pricing' );
$intake_pricing_strings = $intake_collect_strings( [ $intake_pricing['written'] ] );
check( array_column( $intake_pricing_slots, 'slot_id' ) === [ 'section_title', 'section_intro' ] && ! empty( $intake_pricing['response']['ok'] ) && $intake_pricing['calls'] === 1 && $intake_pricing['writes'] === 1, 'Pricing generated slots are limited to the explicitly requested section title and intro' );
foreach ( [ '50 000 ₸', '/мес', 'Малый проект', 'Аудит', 'План', 'Выбрать Старт', '#start', '150 000 ₸', '/год', 'Полный проект', 'Дизайн', 'Разработка', 'Выбрать Проект', '#project', '210 000 ₸', 'Контроль реализации', 'Выезды', 'Отчёт', 'Выбрать Сопровождение', '#support' ] as $pricing_exact ) { check( in_array( $pricing_exact, $intake_pricing_strings, true ), 'Hybrid Pricing exact tier fact survives intake/compiler/readback: ' . $pricing_exact ); }
$intake_pricing_claim_payload = [ 'family' => 'pricing', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Тарифные планы для вашего проекта', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Мы предлагаем гибкие условия сотрудничества, подходящие для задач любого масштаба. Выберите вариант, который соответствует вашим потребностям, и начните работу уже сегодня.', 'fact_refs' => [] ] ] ];
$intake_pricing_claim = $run_services_route( $intake_pricing_prompt, [ provider_reply( wp_json_encode( $intake_pricing_claim_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-refusal-unsupported-pricing-claims' );
$intake_pricing_claim_trace = (array) ( $intake_pricing_claim['response']['diagnostics']['intake'] ?? [] );
check( empty( $intake_pricing_claim['response']['ok'] ) && $intake_pricing_claim['calls'] === 1 && $intake_pricing_claim['writes'] === 0 && $intake_pricing_claim['write_attempts'] === 0 && $intake_pricing_claim['page_data'] === $legacy_page && ( $intake_pricing_claim['error']['code'] ?? '' ) === 'intake_generated_copy_rejected' && ( $intake_pricing_claim['error']['data']['intake']['refusal'] ?? '' ) === 'unsupported_generated_claim', 'Pricing provider copy with ungrounded flexible terms, any-scale scope, and today claims is refused before the transaction' );
check( ! wpae_brief_ir_generated_claims_grounded( 'Гибкие условия доступны сегодня для проектов любого масштаба.', [], [] ) && wpae_brief_ir_generated_claims_grounded( 'Гибкие условия доступны сегодня для проектов любого масштаба.', [ 'fact_1' ], [ 'fact_1' => 'Гибкие условия доступны сегодня для проектов любого масштаба.' ] ) && wpae_brief_ir_generated_claims_grounded( 'Сравните составы тарифов и выберите подходящий вариант.', [], [] ), 'Unsupported commercial claims require exact cited source support while neutral generated copy remains allowed' );
check( ! wpae_brief_ir_generated_text_matches_locale( 'Pricing Plans', 'ru' ) && ! wpae_brief_ir_generated_text_matches_locale( 'Choose the plan that best fits your project needs.', 'ru-RU' ) && wpae_brief_ir_generated_text_matches_locale( 'Тарифы для вашего проекта', 'ru' ) && wpae_brief_ir_generated_text_matches_locale( 'Project pricing options', 'en' ), 'Generated copy must follow the frozen Brief locale without rejecting a matching Russian or English value' );
$intake_pricing_english_payload = [ 'family' => 'pricing', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Pricing Plans', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Choose the plan that best fits your project needs.', 'fact_refs' => [] ] ] ];
$intake_pricing_english = $run_services_route( $intake_pricing_prompt, [ provider_reply( wp_json_encode( $intake_pricing_english_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-refusal-generated-language-mismatch' );
$intake_pricing_english_trace = (array) ( $intake_pricing_english['response']['diagnostics']['intake'] ?? $intake_pricing_english['error']['data']['intake'] ?? [] );
$intake_pricing_english_provider_input = json_decode( (string) ( $intake_pricing_english['http_calls'][0]['body']['messages'][1]['content'] ?? '' ), true );
$intake_pricing_english_system = (string) ( $intake_pricing_english['http_calls'][0]['body']['messages'][0]['content'] ?? '' );
check( empty( $intake_pricing_english['response']['ok'] ) && $intake_pricing_english['calls'] === 1 && $intake_pricing_english['writes'] === 0 && $intake_pricing_english['write_attempts'] === 0 && ( $intake_pricing_english['error']['data']['intake']['refusal'] ?? '' ) === 'generated_locale_mismatch' && ( $intake_pricing_english_trace['output_locale'] ?? '' ) === 'ru' && ( $intake_pricing_english_provider_input['output_locale'] ?? '' ) === 'ru' && str_contains( $intake_pricing_english_system, 'output_locale is canonical' ), 'Ordinary chat rejects English generated Pricing copy for a Russian Brief before any write and sends locale to the provider: ' . wp_json_encode( [ 'error' => $intake_pricing_english['error'], 'trace' => $intake_pricing_english_trace, 'provider_input' => $intake_pricing_english_provider_input, 'system_has_rule' => str_contains( $intake_pricing_english_system, 'output_locale is canonical' ), 'calls' => $intake_pricing_english['calls'], 'writes' => $intake_pricing_english['writes'], 'write_attempts' => $intake_pricing_english['write_attempts'] ], JSON_UNESCAPED_UNICODE ) );

$intake_faq_prompt = "Создай FAQ. Вопрос 1: «Какие сведения нужны для начала?»\nВопрос 2: «Как согласуем состав работ?»\nФакты: На первой встрече обсуждаем задачу и исходные материалы; После изучения исходных материалов согласуем состав работ и смету.\nСформулируй ответы только на основе этих фактов.";
$intake_faq_probe = wpae_brief_ir_parse( $intake_faq_prompt );
$intake_faq_slots = wpae_brief_ir_generated_copy_slots( $intake_faq_probe, $intake_faq_prompt );
$intake_faq_facts = wpae_brief_ir_approved_facts( $intake_faq_probe, $intake_faq_prompt );
$intake_faq_payload = [ 'family' => 'faq', 'generated' => [ [ 'slot_id' => 'faq_1_answer', 'text' => 'На первой встрече обсуждаем задачу и исходные материалы.', 'fact_refs' => [ 'fact_1' ] ], [ 'slot_id' => 'faq_2_answer', 'text' => 'После изучения исходных материалов согласуем состав работ и смету.', 'fact_refs' => [ 'fact_2' ] ] ] ];
$intake_faq = $run_services_route( $intake_faq_prompt, [ provider_reply( wp_json_encode( $intake_faq_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-hybrid-faq' );
$intake_faq_strings = $intake_collect_strings( [ $intake_faq['written'] ] );
check( array_column( $intake_faq_slots, 'slot_id' ) === [ 'faq_1_answer', 'faq_2_answer' ] && count( $intake_faq_facts ) === 2 && ! empty( $intake_faq['response']['ok'] ) && $intake_faq['calls'] === 1 && $intake_faq['writes'] === 1, 'FAQ ordinary chat preserves exact question groups and generates only the two authorized answers' );
check( in_array( 'Какие сведения нужны для начала?', $intake_faq_strings, true ) && in_array( 'Как согласуем состав работ?', $intake_faq_strings, true ) && in_array( 'На первой встрече обсуждаем задачу и исходные материалы.', $intake_faq_strings, true ) && in_array( 'После изучения исходных материалов согласуем состав работ и смету.', $intake_faq_strings, true ) && in_array( 'accordion', $m1_widgets( [ $intake_faq['written'] ] ), true ), 'FAQ native readback keeps question/answer group bindings in a real Accordion' );

$intake_faq_complete_prompt = "Создай блок FAQ в настоящем интерактивном Accordion. Сохрани вопросы точно и в этом порядке:\nВопрос 1: «С чего начинается работа?»\nВопрос 2: «Что подготовить к первой встрече?»\nФакты: На первой встрече команда обсуждает задачу, пожелания и исходные материалы; Можно показать планы помещения, фотографии и список пожеланий. Команда сверяет их с ограничениями пространства, затем согласует состав проектных работ и смету до начала разработки чертежей. Сформулируй ответы на основе только фактов, без новых сроков, обязательств, условий, цен или обещаний. Первый ответ сделай коротким, второй — полным и более длинным. Изображения и CTA не добавляй. Добавь блок к существующей странице.";
$intake_faq_complete_probe = wpae_brief_ir_parse( $intake_faq_complete_prompt );
$intake_faq_complete_facts = wpae_brief_ir_approved_facts( $intake_faq_complete_probe, $intake_faq_complete_prompt );
$intake_faq_complete_fact_texts = array_column( $intake_faq_complete_facts, 'exact_text' );
$intake_faq_complete_expected_facts = [
	'На первой встрече команда обсуждает задачу, пожелания и исходные материалы',
	'Можно показать планы помещения, фотографии и список пожеланий',
	'Команда сверяет их с ограничениями пространства, затем согласует состав проектных работ и смету до начала разработки чертежей',
];
check( $intake_faq_complete_fact_texts === $intake_faq_complete_expected_facts && count( array_filter( $intake_faq_complete_facts, static fn( $fact ): bool => ( $fact['provenance']['label'] ?? '' ) === 'labeled_fact' && substr( $intake_faq_complete_prompt, $fact['source_span'][0], $fact['source_span'][1] - $fact['source_span'][0] ) === $fact['exact_text'] ) ) === 3, 'FAQ facts preserve complete same-line sentences, exact byte spans, and source order: ' . wp_json_encode( [ 'actual' => $intake_faq_complete_fact_texts, 'expected' => $intake_faq_complete_expected_facts, 'facts' => $intake_faq_complete_facts ], JSON_UNESCAPED_UNICODE ) );
$intake_faq_complete_payload = [ 'family' => 'faq', 'generated' => [
	[ 'slot_id' => 'faq_1_answer', 'text' => 'На первой встрече команда обсуждает задачу, пожелания и исходные материалы.', 'fact_refs' => [ 'fact_1' ] ],
	[ 'slot_id' => 'faq_2_answer', 'text' => 'К встрече можно подготовить планы помещения, фотографии и список пожеланий. Команда сверит их с ограничениями пространства и согласует состав проектных работ и смету до чертежей.', 'fact_refs' => [ 'fact_2', 'fact_3' ] ],
] ];
$intake_faq_complete = $run_services_route( $intake_faq_complete_prompt, [ provider_reply( wp_json_encode( $intake_faq_complete_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-faq-complete-labeled-facts' );
$intake_faq_complete_strings = $intake_collect_strings( [ $intake_faq_complete['written'] ] );
$intake_faq_complete_trace = (array) ( $intake_faq_complete['response']['diagnostics']['intake'] ?? [] );
check( ! empty( $intake_faq_complete['response']['ok'] ) && $intake_faq_complete['calls'] === 1 && $intake_faq_complete['writes'] === 1 && ( $intake_faq_complete_trace['generated_slot_count'] ?? 0 ) === 2 && ( $intake_faq_complete['response']['diagnostics']['provider_calls'] ?? 0 ) === 1, 'Production FAQ intake accepts distinct generated answers using all complete labeled facts in one provider call' );
check( in_array( 'Что подготовить к первой встрече?', $intake_faq_complete_strings, true ) && in_array( 'К встрече можно подготовить планы помещения, фотографии и список пожеланий. Команда сверит их с ограничениями пространства и согласует состав проектных работ и смету до чертежей.', $intake_faq_complete_strings, true ) && in_array( 'accordion', $m1_widgets( [ $intake_faq_complete['written'] ] ), true ), 'Grounded FAQ copy retains full second answer and native Accordion structure' );
$intake_faq_repeat_payload = [ 'family' => 'faq', 'generated' => [
	[ 'slot_id' => 'faq_1_answer', 'text' => 'На первой встрече команда обсуждает задачу, пожелания и исходные материалы.', 'fact_refs' => [ 'fact_1' ] ],
	[ 'slot_id' => 'faq_2_answer', 'text' => 'На первой встрече команда обсуждает задачу, пожелания и исходные материалы. Можно показать планы помещения, фотографии и список пожеланий. Команда сверяет их с ограничениями пространства и согласует состав проектных работ и смету до чертежей.', 'fact_refs' => [ 'fact_1', 'fact_2', 'fact_3' ] ],
] ];
$intake_faq_repeated_answer = $run_services_route( $intake_faq_complete_prompt, [ provider_reply( wp_json_encode( $intake_faq_repeat_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-faq-repeated-sibling-copy' );
check( ! empty( $intake_faq_repeated_answer['error'] ) && $intake_faq_repeated_answer['calls'] === 1 && $intake_faq_repeated_answer['writes'] === 0 && $intake_faq_repeated_answer['write_attempts'] === 0 && $intake_faq_repeated_answer['page_data'] === $legacy_page && ( $intake_faq_repeated_answer['error']['data']['intake']['refusal'] ?? '' ) === 'repeated_sibling_sentence', 'Repeated long FAQ answer sentence is refused before transaction without a retry or partial root' );
$intake_faq_missing_fact_payload = [ 'family' => 'faq', 'generated' => [
	[ 'slot_id' => 'faq_1_answer', 'text' => 'На первой встрече команда обсуждает задачу, пожелания и исходные материалы.', 'fact_refs' => [ 'fact_1' ] ],
	[ 'slot_id' => 'faq_2_answer', 'text' => 'К встрече можно подготовить планы помещения, фотографии и список пожеланий.', 'fact_refs' => [ 'fact_2' ] ],
] ];
$intake_faq_missing_fact = $run_services_route( $intake_faq_complete_prompt, [ provider_reply( wp_json_encode( $intake_faq_missing_fact_payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ) ], [], 'intake-faq-unreferenced-labeled-fact' );
check( ! empty( $intake_faq_missing_fact['error'] ) && $intake_faq_missing_fact['calls'] === 1 && $intake_faq_missing_fact['writes'] === 0 && $intake_faq_missing_fact['write_attempts'] === 0 && $intake_faq_missing_fact['page_data'] === $legacy_page && ( $intake_faq_missing_fact['error']['data']['intake']['refusal'] ?? '' ) === 'unreferenced_labeled_fact', 'An unused explicitly labeled FAQ fact refuses before transaction rather than silently disappearing' );

$intake_bad_responses = [
	'invented_number' => [ 'family' => 'hero', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Лучшие решения для 12 семей', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Проектируем дома и общественные пространства под задачи заказчика.', 'fact_refs' => [] ] ] ],
	'invented_url' => [ 'family' => 'hero', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Пространство для жизни', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Обсудите задачу на https://invented.example.', 'fact_refs' => [] ] ] ],
	'unknown_fact_ref' => [ 'family' => 'benefits', 'generated' => [ [ 'slot_id' => 'benefits_1_description', 'text' => 'Сверяем планировочные решения с привычками из задания.', 'fact_refs' => [ 'fact_unknown' ] ], [ 'slot_id' => 'benefits_2_description', 'text' => 'Подбираем местные материалы в соответствии с замыслом.', 'fact_refs' => [ 'fact_2' ] ], [ 'slot_id' => 'benefits_3_description', 'text' => 'Учитываем рельеф участка при разработке решений.', 'fact_refs' => [ 'fact_3' ] ] ] ],
	'duplicate_fact_ref' => [ 'family' => 'benefits', 'generated' => [ [ 'slot_id' => 'benefits_1_description', 'text' => 'Сверяем планировочные решения с привычками из задания.', 'fact_refs' => [ 'fact_1', 'fact_1' ] ], [ 'slot_id' => 'benefits_2_description', 'text' => 'Подбираем местные материалы в соответствии с замыслом.', 'fact_refs' => [ 'fact_2' ] ], [ 'slot_id' => 'benefits_3_description', 'text' => 'Учитываем рельеф участка при разработке решений.', 'fact_refs' => [ 'fact_3' ] ] ] ],
	'duplicate_slot' => [ 'family' => 'hero', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Архитектура для жизни', 'fact_refs' => [] ], [ 'slot_id' => 'section_title', 'text' => 'Второй заголовок', 'fact_refs' => [] ] ] ],
	'wrong_family' => [ 'family' => 'about', 'generated' => [ [ 'slot_id' => 'section_title', 'text' => 'Архитектура для жизни', 'fact_refs' => [] ], [ 'slot_id' => 'section_intro', 'text' => 'Проектируем дома и пространства.', 'fact_refs' => [] ] ] ],
];
$intake_negative_hero_prompt = 'Создай Hero без фото. Напиши заголовок и описание для архитектурной студии.';
foreach ( $intake_bad_responses as $name => $payload ) {
	$prompt = in_array( $name, [ 'unknown_fact_ref', 'duplicate_fact_ref' ], true ) ? $intake_benefits_prompt : $intake_negative_hero_prompt;
	$response = provider_reply( wp_json_encode( $payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) );
	$schema_retry = in_array( $name, [ 'duplicate_slot', 'wrong_family' ], true );
	$responses = $schema_retry ? [ $response, $response ] : [ $response ];
	$result = $run_services_route( $prompt, $responses, [], 'intake-refusal-' . $name );
	check( ! empty( $result['error'] ) && $result['calls'] === ( $schema_retry ? 2 : 1 ) && ( $result['error']['data']['write_count'] ?? null ) === 0 && $result['writes'] === 0 && $result['write_attempts'] === 0 && $result['page_data'] === $legacy_page, 'Typed intake ' . $name . ' rejection is bounded, no-write, and cannot enter legacy generation' );
	if ( $name === 'unknown_fact_ref' ) { check( ( $result['error']['data']['intake']['semantic_validation_result'] ?? '' ) === 'semantic_provenance_failure' && ( $result['error']['data']['intake']['retry_count'] ?? -1 ) === 0, 'Semantic provenance failure is classified separately and never schema-retried' ); }
}
$intake_invalid_json = $run_services_route( $intake_negative_hero_prompt, [ provider_reply( 'not JSON' ), provider_reply( 'still not JSON' ) ], [], 'intake-refusal-invalid-schema' );
$intake_timeout = $run_services_route( $intake_negative_hero_prompt, [ new WP_Error( 'http_request_failed', 'simulated intake timeout' ) ], [], 'intake-refusal-timeout' );
$intake_missing_slot_reply = provider_reply( wp_json_encode( [ 'family' => 'hero', 'generated' => [] ] ) );
$intake_missing_slot = $run_services_route( $intake_negative_hero_prompt, [ $intake_missing_slot_reply, $intake_missing_slot_reply ], [], 'intake-refusal-missing-slot' );
check( ! empty( $intake_invalid_json['error'] ) && $intake_invalid_json['calls'] === 2 && ( $intake_invalid_json['error']['data']['intake']['retry_count'] ?? 0 ) === 1 && ( $intake_invalid_json['error']['data']['intake']['attempts'][0]['schema_validation_result'] ?? '' ) === 'retryable_schema_failure' && ( $intake_invalid_json['error']['data']['intake']['attempts'][1]['schema_validation_result'] ?? '' ) === 'retryable_schema_failure' && $intake_invalid_json['writes'] === 0 && $intake_invalid_json['page_data'] === $legacy_page, 'Malformed JSON at stop receives one syntax-only retry, then refuses without a third attempt or transaction' );
check( ! empty( $intake_timeout['error'] ) && $intake_timeout['calls'] === 1 && ( $intake_timeout['error']['data']['intake']['refusal'] ?? '' ) === 'provider_timeout' && ( $intake_timeout['error']['data']['intake']['semantic_validation_result'] ?? '' ) === 'not_checked' && ( $intake_timeout['error']['data']['intake']['attempts'][0]['transport_error_code'] ?? '' ) === 'http_request_failed' && $intake_timeout['writes'] === 0 && $intake_timeout['page_data'] === $legacy_page, 'Intake timeout is identified from its transport error, is not retried, and never writes partial content' );
check( ! empty( $intake_missing_slot['error'] ) && $intake_missing_slot['calls'] === 2 && $intake_missing_slot['writes'] === 0 && $intake_missing_slot['page_data'] === $legacy_page, 'Missing authorized generated slots refuse after one schema-preserving retry without placeholder copy or partial root' );
$intake_team_strict = $run_services_route( 'Создай блок команды для архитектурной студии. Напиши представление команды.', [], [], 'intake-strict-team' );
check( ! empty( $intake_team_strict['error'] ) && $intake_team_strict['calls'] === 0 && $intake_team_strict['writes'] === 0 && $intake_team_strict['page_data'] === $legacy_page, 'Team remains entity-bound and does not enter generic invented-copy generation' );

$intake_cta_prompt = 'Создай самостоятельный CTA-блок. Заголовок: «Напишите нам ✨». Описание: «Обсудим задачу и выберем удобный способ связи». Основная кнопка: «Написать», ссылка mailto:hello@example.test. Вторая кнопка: «Позвонить», ссылка tel:+77000000000.';
$intake_cta = $run_services_route( $intake_cta_prompt, [], [], 'intake-exact-cta' );
$intake_cta_strings = $intake_collect_strings( [ $intake_cta['written'] ] );
check( ! empty( $intake_cta['response']['ok'] ) && $intake_cta['calls'] === 0 && $intake_cta['writes'] === 1, 'Exact CTA copy compiles locally without a needless provider intake call' );
check( in_array( 'Напишите нам ✨', $intake_cta_strings, true ) && in_array( 'mailto:hello@example.test', $intake_cta_strings, true ) && in_array( 'tel:+77000000000', $intake_cta_strings, true ), 'Exact CTA keeps Cyrillic emoji and byte-accurate mailto/tel destinations' );
