const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const llm = read('includes/llm/llm.php');
const editor = read('includes/elementor/editor-chat.php');
const js = read('assets/js/elementor-llm-chat.js');
const routes = read('includes/rest/routes.php');
const bootstrap = read('wp-ai-executor.php');
const dashboard = read('includes/admin/dashboard.php');

assert.match(llm, /'openai'/);
assert.match(llm, /'deepseek'/);
assert.match(llm, /'openrouter'/);
assert.match(llm, /'model' => 'openrouter\/free'/);
assert.match(llm, /\$provider === 'custom'/);
assert.match(llm, /wpae_vision_encrypt_api_key/);
assert.match(llm, /wp_safe_remote_post/);
assert.match(llm, /WPAE_LLM_CALL_LIMIT/);
assert.match(llm, /wpae_capability_enabled\( 'llm_chat' \)/);
assert.match(llm, /wpae_llm_validate_base_url/);
assert.match(llm, /wpae_llm_response_diagnostics/);
assert.match(llm, /output_text/);
assert.match(llm, /max_completion_tokens' => \$action_request \? 3000 : 1200/);
assert.match(llm, /wpae_llm_is_action_request/);
assert.match(llm, /wpae_llm_execute_action/);
assert.match(llm, /transaction_visual_regression/);
assert.match(llm, /insert_elements/);
assert.match(llm, /wpae_elementor_normalize_data/);
assert.match(js, /body\.details\.error/);
assert.match(js, /event\.key === 'Enter'/);
assert.match(js, /event\.shiftKey/);
assert.match(js, /event\.isComposing/);
assert.match(js, /form\.requestSubmit\(\)/);
assert.match(js, /errorData\.details/);
assert.match(routes, /'\/llm\/chat'/);
assert.match(routes, /'callback'\s*=>\s*'wpae_llm_chat'/);
assert.match(editor, /wp_create_nonce\( 'wp_rest' \)/);
assert.match(editor, /\$_GET\['action'\].*elementor/s);
assert.match(editor, /admin_enqueue_scripts/);
assert.match(editor, /wpae-elementor-llm-chat/);
assert.match(dashboard, /data-base-url/);
assert.match(dashboard, /••••••••••••/);
assert.doesNotMatch(editor, /wpae_get_key\(|api_key_encrypted|['"]api_key['"]/);
assert.doesNotMatch(js, /X-AI-Key|X-WPAE-API-Key|api_key/i);
assert.match(bootstrap, /includes\/llm\/llm\.php/);
assert.match(bootstrap, /includes\/elementor\/editor-chat\.php/);
console.log('llm chat contract: OK');
