const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const llm = read('includes/llm/llm.php');
const vision = read('includes/vision/vision.php');
const editor = read('includes/elementor/editor-chat.php');
const js = read('assets/js/elementor-llm-chat.js');
const routes = read('includes/rest/routes.php');
const bootstrap = read('wp-ai-executor.php');
const dashboard = read('includes/admin/dashboard.php');

assert.match(llm, /'openai'/);
assert.match(llm, /'deepseek'/);
assert.match(llm, /'openrouter'/);
assert.match(llm, /'model' => 'openrouter\/free'/);
assert.match(vision, /gemini-3\.5-flash-lite/);
assert.match(vision, /gemini-2\.5-flash-lite/);
assert.match(vision, /\$model === '' \|\| \( \$provider === 'gemini'/);
assert.match(llm, /Каждый container обязан содержать заполненные native widgets/);
assert.match(llm, /ровно 1 корневой контейнер и 3–5 вложенных виджетов/);
assert.match(llm, /массив elements обязан содержать ровно один объект elType=container/);
assert.match(llm, /\$provider === 'custom'/);
assert.match(llm, /wpae_vision_encrypt_api_key/);
assert.match(llm, /wp_safe_remote_post/);
assert.match(llm, /WPAE_LLM_CALL_LIMIT/);
assert.match(llm, /wpae_capability_enabled\( 'llm_chat' \)/);
assert.match(llm, /wpae_llm_validate_base_url/);
assert.match(llm, /wpae_llm_response_diagnostics/);
assert.match(llm, /wpae_llm_provider_error_message/);
assert.match(llm, /provider_error_code/);
assert.match(js, /provider_message/);
assert.match(llm, /output_text/);
assert.match(llm, /max_completion_tokens' => \$action_request \? 8000 : 1200/);
assert.match(llm, /response_format.*json_object/);
assert.match(llm, /require_parameters.*true/);
assert.match(llm, /Не возвращай URL, HTTP-запросы/);
assert.match(llm, /structured_route_rejected/);
assert.match(llm, /unset\( \$request_body\['response_format'\], \$request_body\['provider'\] \)/);
assert.match(llm, /function wpae_llm_provider_request/);
assert.match(llm, /Исправь Elementor action JSON/);
assert.match(llm, /action_repair/);
assert.match(llm, /Ограничения компактности action-JSON/);
assert.match(llm, /likely_truncated/);
assert.match(js, /finish_reason/);
assert.match(llm, /wpae_llm_is_action_request/);
assert.match(llm, /is_string\( \$decoded \)/);
assert.match(llm, /\$nested = json_decode/);
assert.match(llm, /wpae_llm_execute_action/);
assert.match(llm, /transaction_visual_regression/);
assert.match(llm, /transaction_visual_regression', ! \$initial_page/);
assert.match(llm, /insert_elements/);
assert.match(llm, /wpae_elementor_normalize_data/);
assert.match(js, /body\.details\.error/);
assert.match(js, /event\.key === 'Enter'/);
assert.match(js, /event\.shiftKey/);
assert.match(js, /event\.isComposing/);
assert.match(js, /form\.requestSubmit\(\)/);
assert.match(js, /errorData\.details/);
assert.match(js, /navigator\.clipboard\.writeText/);
assert.match(js, /strings\.copyLog/);
assert.match(js, /diagnostics\.error/);
assert.match(js, /typeof errorData\.details === 'string'/);
assert.match(js, /diagnostics\.update_error/);
assert.match(js, /diagnostics\.blocking_errors/);
assert.match(js, /formatStep/);
assert.match(js, /body\.steps/);
assert.match(js, /addStepMessages/);
assert.match(js, /reloadPreview/);
assert.match(js, /getPreviewWidgetCount/);
assert.match(js, /minimumWidgetCount/);
assert.match(js, /searchParams\.set\('ver'/);
assert.match(js, /progressMessages/);
assert.match(js, /failedChecks/);
assert.match(js, /received_action/);
assert.match(js, /wpae-llm-chat-log-v1/);
assert.match(js, /JSON\.stringify/);
assert.match(editor, /'copyLog' => 'Копировать JSON'/);
assert.match(llm, /_wpae_allow_initial_data/);
assert.match(llm, /wpae_apply_design_token_map/);
assert.match(llm, /blocking_errors/);
assert.match(llm, /wpae_llm_is_list/);
assert.match(llm, /received_action/);
assert.match(llm, /command_decode/);
assert.match(llm, /native_normalize/);
assert.match(llm, /elementor_update/);
assert.match(llm, /wpae_llm_count_widgets/);
assert.match(llm, /native_widgets/);
assert.match(llm, /сбалансированную композицию/);
assert.match(llm, /чрезмерно широких колонок/);
assert.match(llm, /failed_checks/);
assert.match(llm, /failure_details/);
assert.match(llm, /decoded_action/);
assert.match(llm, /execution_trace/);
assert.match(llm, /guided_context/);
assert.match(llm, /action_content_gate/);
assert.match(llm, /wpae_agent_prompt/);
assert.match(llm, /wpae_get_enabled_skills_for_guide/);
assert.match(read('includes/elementor/normalize.php'), /mapped_native_widget_content/);
assert.match(read('includes/elementor/page-update.php'), /_wpae_allow_initial_data/);
assert.match(read('includes/elementor/page-update.php'), /! empty\( \$existing_data \).*transaction_visual_regression/);
assert.match(read('includes/elementor/page-update.php'), /get_post_status\( \$post_id \) === 'publish'/);
assert.match(routes, /'\/llm\/chat'/);
assert.match(routes, /'callback'\s*=>\s*'wpae_llm_chat'/);
assert.match(routes, /'\/llm\/vision-review'/);
assert.match(routes, /'callback'\s*=>\s*'wpae_vision_editor_review'/);
assert.match(editor, /wp_create_nonce\( 'wp_rest' \)/);
assert.match(editor, /\$_GET\['action'\].*elementor/s);
assert.match(editor, /admin_enqueue_scripts/);
assert.match(editor, /wpae-elementor-llm-chat/);
assert.match(editor, /pluginVersion/);
assert.match(editor, /providerLabel/);
assert.match(editor, /postStatus/);
assert.match(editor, /'model'\s*=>/);
assert.match(js, /wpae-llm-meta/);
assert.match(js, /pluginVersion/);
assert.match(dashboard, /data-base-url/);
assert.match(dashboard, /••••••••••••/);
assert.match(dashboard, /wpae-vision-api-key[\s\S]*has_api_key/);
assert.doesNotMatch(editor, /wpae_get_key\(|api_key_encrypted|['"]api_key['"]/);
assert.doesNotMatch(js, /X-AI-Key|X-WPAE-API-Key|api_key/i);
assert.match(js, /capturePreviewScreenshot/);
assert.match(js, /refreshWpPreview/);
assert.match(js, /document\/save/);
assert.match(js, /syncEditorElements/);
assert.match(js, /document\/elements\/create/);
assert.match(llm, /'editor_sync' =>/);
assert.match(js, /requestVisionReview/);
assert.match(js, /config\.postStatus === 'publish'/);
assert.match(js, /vision_capture_error/);
assert.match(js, /rollback_snapshot_id/);
assert.match(editor, /captureScript/);
assert.match(editor, /reviewEndpoint/);
assert.match(bootstrap, /includes\/llm\/llm\.php/);
assert.match(bootstrap, /includes\/elementor\/editor-chat\.php/);
console.log('llm chat contract: OK');
