const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const routes = read('includes/rest/routes.php');
const dashboard = read('includes/admin/dashboard.php');
const vision = read('includes/vision/vision.php');
const transactions = read('includes/elementor/transactions.php');

assert.doesNotMatch(routes, /register_rest_route\( 'ai-executor\/v1', '\/key'/);
assert.match(dashboard, /if \( ! current_user_can\( 'manage_options' \) \) \{\s*return;/);
assert.match(vision, /function wpae_vision_consume_provider_slot/);
assert.match(vision, /function wpae_validate_vision_provider_report/);
assert.match(vision, /wpae_vision_provider_invalid_report/);
assert.match(vision, /function wpae_validate_vision_report_scope/);
assert.match(vision, /function wpae_vision_editor_review/);
assert.match(vision, /function wpae_vision_render_context/);
assert.match(vision, /function wpae_vision_compare_text/);
assert.match(vision, /function wpae_vision_requested_phrases/);
assert.match(vision, /function wpae_vision_is_verified_missing_content_finding/);
assert.match(vision, /A CTA phrase present in text_excerpt proves the CTA text exists/);
assert.match(vision, /editor_review_is_advisory/);
assert.match(vision, /Ignore Elementor editor chrome/);
assert.match(vision, /render_context/);
assert.match(vision, /text_excerpt/);
assert.match(vision, /target_element_ids/);
assert.match(vision, /content_fidelity/);
assert.match(vision, /objective text_excerpt is authoritative evidence/);
assert.match(vision, /'render_context' => \$request->get_param\( 'render_context' \)/);
assert.match(vision, /'rolled_back' => false/);
assert.match(vision, /wpae_vision_capture_failed/);
assert.match(vision, /provider_http_status/);
assert.match(vision, /provider_message/);
assert.match(vision, /\$quality_failed = ! empty\( \$gate\['quality_failed'\] \)/);
assert.match(vision, /'blocking_advisory' => ! empty\( \$gate\['blocking'\] \)/);
assert.match(vision, /'quality_warning' => \$quality_failed/);
assert.doesNotMatch(vision, /'quality_failed' => false/);
assert.match(vision, /score_below_floor/);
assert.match(transactions, /wpae_vision_unverified_report/);

console.log('vision security contract: OK');
