<?php

defined( 'ABSPATH' ) || exit;

function wpae_get_guide(): WP_REST_Response {
    return new WP_REST_Response( wpae_agent_guide(), 200 );
}

function wpae_agent_guide(): array {
    return [
        'name' => 'WP AI Executor Agent Guide',
        'version' => 'v02.05.45',
        'plugin_version' => WPAE_VERSION,
        'purpose' => 'Use this guide before automating WordPress and Elementor through WP AI Executor.',
        'embedded_skill_packs' => [
            'frontend_design' => 'Distilled frontend-design rules for distinctive visual direction, typography, layout, motion, and copy.',
            'wordpress_elementor_dev' => 'Distilled WordPress/Elementor development rules for native Elementor data, REST execution, security, and verification.',
            'jezweb_claude_skills' => 'Distilled jezweb/claude-skills workflows for WordPress Elementor, landing pages, design review, and color palettes.',
        ],
        'custom_skills' => wpae_get_enabled_skills_for_guide(),
        'project_design_tokens' => wpae_get_project_design_tokens(),
        'project_design_system' => wpae_build_project_design_system(),
        'jezweb_claude_skills' => wpae_get_jezweb_claude_skills_pack(),
        'capabilities' => wpae_get_capabilities_payload(),
        'wordpress_health_policy' => [
            'endpoint' => 'GET /wp-json/ai-executor/v1/health',
            'quick_mode' => 'Use ?mode=quick for cached read-only PHP, database, cron, memory, disk, autoload, debug, and update checks.',
            'deep_mode' => 'Use ?mode=deep&refresh=1 only when investigating availability or 504/timeout symptoms; it adds WordPress loopback and REST self-checks with five-second timeouts.',
            'agent_rule' => 'Read summary, checks, recommendations, and history. Report every critical/warning check with its code, details, and next safe action. Do not claim that the plugin can diagnose a fully blocked PHP-FPM pool from inside WordPress.',
            'safety' => 'The endpoint is authenticated and read-only. It never restarts services, clears caches, deletes logs, changes options, or writes server files.',
        ],
        'repeated_agent_error_audit_policy' => [
            'returned_in' => [ 'POST /elementor/visual-audit', 'POST /audit' ],
            'rule' => 'Agents must read repeated_agent_error_audit and fix every fail check before claiming success; warn checks must be either fixed or explicitly explained.',
            'checks' => [
                'legacy_sections_columns',
                'snake_case_widget_type',
                'html_widget_layout_or_content',
                'script_injected_native_css',
                'heading_typography_important_override',
                'excessive_local_typography_overrides',
                'design_system_marker_drift',
                'fixed_px_layout_risk',
            ],
        ],
        'guide_token_protocol' => [
            'required_for_write_endpoints' => true,
            'session_endpoint' => 'POST /wp-json/ai-executor/v1/guide/session',
            'ack_endpoint' => 'POST /wp-json/ai-executor/v1/guide/ack',
            'required_write_headers' => [
                'X-WPAE-Guide-Token',
                'X-WPAE-Guide-Hash',
            ],
            'ttl_minutes' => 15,
            'storage' => 'Guide sessions are stored as individual wp_options plus a legacy index; guide tokens are stored by token hash so write validation does not depend only on one shared session array.',
            'ack_body_formats' => [
                'application/json body: {"guide_session_id":"...","ack":{...}}',
                'raw JSON body fallback even when Content-Type is missing/wrong',
                'form fields: guide_session_id plus read_agent_prompt/read_custom_skills/read_capabilities/will_follow_skills/will_follow_runtime_rules',
            ],
            'rule' => 'Before any write endpoint, create a guide session, read /guide and /capabilities, acknowledge all required fields, then send the returned guide token and hash with the write request.',
        ],
        'v02_08_16_behavior_notes' => [
            'rule' => 'Agents must account for current WP AI Executor runtime behavior instead of assuming older file-based or broad-rollback behavior.',
            'rollback_scope' => [
                'behavior' => 'Rollback restores the post record plus plugin-managed Elementor/WPAE meta only.',
                'managed_post_meta' => wpae_managed_rollback_post_meta_keys(),
                'agent_instruction' => 'Do not expect /rollback to delete or restore unrelated third-party post meta such as SEO, CRM, analytics, theme, or custom plugin fields.',
            ],
            'elementor_page_orphan_cleanup' => [
                'behavior' => 'If /elementor/page creates a new page but Elementor metadata saving fails, the plugin attempts to delete that newly created page immediately.',
                'response_signal' => 'Failure responses may include cleanup.created_post_deleted and cleanup.reason.',
                'agent_instruction' => 'On /elementor/page failure, inspect cleanup before retrying; do not manually hunt for orphan pages unless cleanup failed.',
            ],
            'media_upload_signature_check' => [
                'behavior' => '/media/upload validates binary file signatures for JPEG, PNG, WebP, GIF, and PDF before writing to the media library.',
                'agent_instruction' => 'The declared mime_type must match the actual base64 content. If rejected, fix the source bytes or mime_type; do not retry with a fake extension.',
                'error' => 'Media binary signature does not match mime_type.',
            ],
            'exports_storage' => [
                'behavior' => '/exports/create stores short-lived JSON exports in wp_options and returns an authenticated /exports/{id} endpoint.',
                'summary_endpoint' => 'GET /wp-json/ai-executor/v1/exports returns metadata only, never raw export JSON.',
                'prune_endpoint' => 'POST /wp-json/ai-executor/v1/exports/prune removes expired wp_options export records and requires the exports capability plus guide token.',
                'agent_instruction' => 'Never expect public uploads export files or a public URL from /exports/create.',
            ],
        ],
        'agent_prompt' => wpae_agent_prompt(),
        'workflow' => [
            '1. Inspect WordPress, PHP, theme, and Elementor status with a small read-only PHP request.',
            '2. Before any page or page-block work, call /elementor/design-system and treat it as the single style source.',
            '3. For page work, call /elementor/blueprint after /elementor/design-system before composing or writing Elementor data.',
            '3a. Design mobile first: define mobile stacking, type scale, spacing, CTA visibility, tap targets, and responsive Elementor settings before expanding tablet and desktop layouts.',
            '4. Prefer /elementor/design-system, /elementor/blueprint, /elementor/recipes, /elementor/compose, /elementor/normalize, /elementor/validate, /elementor/visual-audit, /elementor/editability-audit, /elementor/typography-unlock, /elementor/resolve-typography-overrides, /elementor/css-to-native, /elementor/patch, /elementor/page, and /elementor/update over raw PHP through /run.',
            '4a. Never use /run to bypass /elementor/update, design-system marker classes, dry_run, or Elementor preflight; direct _elementor_data changes through /run are validated by the same contract and rolled back on failure.',
            '4b. If an existing page has old or different wpae-system-* classes, migrate it to the current main design system with /elementor/normalize, then run /elementor/update dry_run; preserve non-WPAE custom classes.',
            '4c. Never ask for WP Admin login/password, admin cookies, nonces, or browser sessions. Do not use Playwright/WP Admin/Elementor editor for writes; browser automation is allowed only to inspect public pages after API writes.',
            '5. Before building a new page, call /elementor/blueprint with subject, audience, goal, offer, language, style, proof points, and CTA labels. For complex or non-standard sections, call /elementor/recipes, choose a recipe/variant, then call /elementor/compose with slots.',
            '6. Use /elementor/normalize when Elementor JSON contains legacy sections/columns, widget_type, missing widgetType, missing settings, missing elements arrays, incomplete container defaults, or missing design-system marker classes.',
            '7. Use /elementor/validate, /elementor/visual-audit, or dry_run=true on /elementor/patch, /elementor/page, and /elementor/update before a real write when building complex pages; structured writes also run strict preflight checks.',
            '8. Use native Elementor Flexbox Containers only for layout: elType=container plus native widgets. Never use legacy elType=section or elType=column.',
            '9. Never create external files. Use WordPress APIs and database metadata only; no temp files, loaders, mu-plugins, PHP/JS/CSS/JSON files, or filesystem writes.',
            '10. Design the page before building: define subject, audience, job, palette, type roles, layout, and one signature element inside the returned design system.',
            '11. Prefer rem/em for spacing and typography, vh/svh for viewport-height sections, and %/flex/max-width constraints for widths; use px only for small exceptions or Elementor compatibility.',
            '12. Change element styles through native Elementor settings/style controls first; use scoped CSS only for exceptional enhancements that cannot reasonably be expressed with native settings.',
            '13. On existing pages, preserve unrelated working CSS/JS/WebGL/Three.js/GSAP/canvas/shader/animation HTML widgets and scoped CSS; do not perform a page-wide restyle or cleanup unless explicitly requested.',
            '13a. Protected enhancement zones are enforced on structured updates. Do not modify or remove them unless the task explicitly requires it; then send allow_protected_zone_changes=true with a concrete protected_zone_reason and verify the public animation afterwards.',
            '14. Save the returned rollback_snapshot_id after writes and use /rollback if the result is wrong.',
            '14a. If /rollback returns ok=false, stop. Report its status/error/restored_posts details, keep the retained snapshot, and do not attempt a manual metadata rewrite, /run workaround, WP Admin edit, or browser-based write.',
            '15. Verify with /audit, /elementor/visual-audit, /elementor/editability-audit, /visual-audit, HTTP status, permalink, post status, _elementor_edit_mode, _elementor_data, visible HTML text, and inspect any html widgets if present.',
            '16. After any page write, rollback, typography migration, or revision restore, perform real browser screenshot verification on the public URL before claiming success; HTML/CSS audits alone are not enough.',
            '17. Use /logs for recent operation metadata when debugging, but never expect raw payloads or secrets there.',
            '18. Read preflight and agent_conformance in write responses and fix weak/blocked criteria, including design quality gates, before considering the task complete.',
            '19. If any endpoint or verification step fails, report concrete error details: endpoint/action, HTTP status or exception, plugin error code/message, details/preflight/blocking_errors, and the next safe fix.',
        ],
        'frontend_design' => [
            'principles' => [
                'Avoid generic template aesthetics; ground the visual direction in the subject matter.',
                'Open with a hero that states a clear design thesis.',
                'Choose a compact color system, intentional typography roles, and one memorable signature element.',
                'Use structure as information, not decoration. Numbering should mean sequence.',
                'Keep copy specific, active, and useful from the visitor side of the screen.',
                'Spend boldness in one place; keep the rest disciplined and responsive.',
            ],
            'anti_generic_defaults' => [
                'Do not default to a generic hero, generic gradient cards, generic dark SaaS page, or one-note palette.',
                'Do not use decorative numbering unless the content is actually sequential.',
                'Do not use stock-like filler sections; every section must move the visitor toward the page job.',
                'Do not stop at a technically valid layout; evaluate whether the page looks intentionally designed.',
            ],
            'planning_template' => [
                'subject' => 'What is being sold or explained?',
                'audience' => 'Who must understand and act?',
                'single_job' => 'What should the page make the visitor do?',
                'palette' => '4-6 named hex colors.',
                'type_roles' => 'Display, body, and utility/caption roles.',
                'layout' => 'Short section map or wireframe.',
                'signature' => 'One distinctive element justified by the brief.',
            ],
            'design_quality_bar' => [
                'Hero must be the design thesis and should contain the page signature.',
                'Typography must use deliberate roles: display, body, utility/caption.',
                'Mobile-first is mandatory: mobile layout, readable type, tap targets, CTA visibility, and section order come before desktop polish.',
                'Layout must be stable at desktop, tablet, and mobile widths.',
                'Use responsive units deliberately: rem/em for spacing and type, vh/svh for viewport-height sections, and percentages/flex constraints for width.',
                'Motion must support comprehension: reveal, hover, progress, or focused ambient animation.',
                'Copy must be concrete and action-oriented.',
                'Native Elementor output must pass design quality gates: heading hierarchy, native spacing, visible CTA, responsive settings, deliberate palette, and populated content.',
            ],
            'project_tokens_rule' => 'Use project_design_tokens from this guide as the site visual system. They override generic defaults unless the user explicitly asks for a different direction.',
            'design_system_first_rule' => 'Before creating a page or adding a page block, call /elementor/design-system. All later blocks must reuse the same system_id, palette, type roles, spacing, radii, button style, and tone.',
            'native_style_first_rule' => 'When changing any element style, write it to native Elementor settings/style controls first. CSS is only an exception for complex behavior, animations, hover/focus refinements, browser fixes, or specificity conflicts after native settings exist.',
            'elementor_editor_editability_rule' => 'All design properties that Elementor can edit must remain editable through native Elementor controls/settings. Native settings are the editable source of truth, not something to delete; only remove local overrides when the user explicitly asks for global inheritance/design-token control.',
            'global_typography_editability_rule' => 'For typography that the user should control globally in Elementor, do not hardcode typography_* overrides on every widget. Use global typography roles, inherited/container typography, or leave widget typography unset; local typography_* settings are allowed only for deliberate exceptions such as a hero display wordmark.',
        ],
        'jezweb_claude_skills' => [
            'source' => 'https://github.com/jezweb/claude-skills',
            'rule' => 'Apply the distilled jezweb workflows when they overlap with WordPress, Elementor, landing pages, design review, color palettes, responsiveness, and production verification.',
            'executor_adaptation' => [
                'Replace upstream standalone HTML output with editable Elementor native containers/widgets.',
                'Replace WP-CLI/browser-only structural edits with WP AI Executor safe endpoints whenever possible.',
                'Use /elementor/design-system before landing page or block work.',
                'Use /elementor/visual-audit as the design-review gate.',
                'Use project design tokens as the color-palette output target.',
                'Do not create external files even if an upstream skill would normally write artifacts.',
            ],
        ],
        'wordpress_elementor' => [
            'stack' => [
                'Remote WordPress site',
                'Elementor only',
                'WP AI Executor as the automation bridge',
                'No Oxygen',
                'No Novamira',
                'HTML widget only for small JS snippets or enhancement code that needs markup/script; CSS-only exceptions belong in the target element settings.custom_css first',
                'No WP Admin or Elementor editor writes through Playwright/browser automation',
            ],
            'browser_admin_policy' => [
                'rule' => 'Do not ask the user for WP Admin login/password, admin cookies, browser sessions, or REST nonces. Do not use WP Admin or Elementor editor for edits.',
                'allowed_browser_use' => 'Playwright/browser automation is allowed only for public-page inspection after REST API writes, such as screenshots, click checks, layout checks, and visible content verification.',
                'required_edit_path' => 'All WordPress/Elementor changes must go through WP AI Executor REST endpoints with X-AI-Key and guide-token headers for writes.',
                'auth_debugging' => 'If a request returns 401/403, verify the header name is X-AI-Key and report endpoint/status/body; do not assume key rotation and do not request credentials.',
            ],
            'filesystem_policy' => [
                'required' => true,
                'rule' => 'Do not create, modify, rename, copy, chmod, or delete files on the WordPress server through WP AI Executor.',
                'forbidden' => [
                    'Temporary loaders such as elem-loader.php.',
                    'Files in /tmp, wp-content/mu-plugins, wp-content/plugins, wp-content/themes, or uploads created as implementation scratch space.',
                    'External PHP, JS, CSS, JSON, base64, cache, or helper files.',
                    'Direct filesystem or shell/process calls such as file_put_contents, fopen, fwrite, mkdir, unlink, rename, copy, chmod, ZipArchive, Phar, WP_Filesystem, wp_mkdir_p, exec, shell_exec, system, passthru, proc_open, and popen.',
                ],
                'allowed_instead' => [
                    'Use wp_insert_post, wp_update_post, update_post_meta, update_option, delete_option, and Elementor metadata.',
                    'Use Elementor cache APIs to clear/regenerate generated CSS; do not write CSS files manually.',
                    'Return data directly from /run instead of writing temporary files.',
                    'Use /media/upload for validated media library files.',
                    'Use /exports/create for short-lived JSON exports stored in wp_options; fetch them through the authenticated /exports/{id} endpoint and never expect public uploads URLs.',
                ],
                'runtime_enforcement' => 'By default, /run rejects common filesystem write/delete operations unless the site owner enables the filesystem_writes capability or WP_AI_EXECUTOR_ALLOW_FILE_WRITES is explicitly defined.',
                'self_update_policy' => [
                    'endpoint' => 'POST /wp-json/ai-executor/v1/self-update',
                    'rule' => 'Plugin self-update is allowed only through the dedicated self-update endpoint, never through arbitrary /run filesystem writes.',
                    'source' => 'Only allowlisted raw GitHub URLs from DiasMazhenov/wp-ai-executor ending in wp-ai-executor.php are accepted.',
                    'target' => 'The endpoint writes only to the current plugin file (__FILE__) after validating required plugin markers.',
                    'dry_run' => 'Pass dry_run=true to compare hashes without writing.',
                ],
                'package_update_policy' => [
                    'endpoint' => 'POST /wp-json/ai-executor/v1/self-update-package',
                    'source' => 'Only an immutable https://github.com/DiasMazhenov/wp-ai-executor/archive/<40-char-commit-sha>.zip URL is accepted.',
                    'validation' => 'ZIP must include wpae-package.json with SHA-256 for every file; only wp-ai-executor.php and includes/*.php or includes/*.json paths are accepted.',
                    'rollout' => 'Modules are written before the bootstrap entrypoint, which is replaced last. Use dry_run=true before a live package rollout.',
                ],
            ],
            'custom_skills_policy' => [
                'endpoint' => 'GET/POST/DELETE /wp-json/ai-executor/v1/skills plus GET /skills/export, POST /skills/import, and POST /skills/import-url',
                'storage' => 'Skills are stored in wp_options as text/JSON, not as files.',
                'rule' => 'Agents must read every enabled custom_skills item in this guide before any WordPress/Elementor work and apply them as mandatory project rules by priority. If a custom skill conflicts with WP AI Executor policy, WP AI Executor policy wins.',
                'github_import' => 'GitHub skills are downloaded by the plugin, normalized, stored in wp_options, included in guide_hash, and exposed through /guide so agents do not need remote internet access to read them.',
                'limits' => 'Each skill content is limited to 120 KB and is never executed as code.',
                'bundle_import_export' => 'Skill bundles are JSON objects with schema=wp-ai-executor.skill-bundle and a skills array. Import mode can be merge or replace. Bundles are stored in the database only.',
                'enforceable_rules' => [
                    'forbid_elementor_eltype',
                    'require_widget_key',
                    'forbid_widget_key',
                    'allow_widget_type',
                    'forbid_widget_type',
                    'require_widget_setting',
                    'require_container_setting',
                    'forbid_html_pattern',
                ],
            ],
        'design_system_policy' => [
            'endpoint' => 'POST /wp-json/ai-executor/v1/elementor/design-system',
            'required' => true,
                'rule' => 'Before creating a page or adding any new page block, create/read the design system and reuse it as the single visual source of truth.',
                'write_enforcement' => 'POST /elementor/page and POST /elementor/update reject Elementor data whose top-level containers miss required_root_classes or do not use project palette tokens.',
                'required_marker' => 'Every top-level page/block container must include required_root_classes in settings._css_classes.',
                'block_rule' => 'A later block must inherit the same system_id, palette, typography roles, spacing, radii, button style, tone, and component grammar as the existing page.',
            'normalize_support' => 'POST /elementor/normalize adds the required design-system marker classes to top-level containers when missing.',
            'migration_rule' => 'If an existing page has old or different wpae-system-* marker classes, /elementor/normalize removes the old system marker, adds the current required_root_classes, preserves non-WPAE custom classes, and returns migrated_design_system_marker changes.',
            'agent_rule' => 'On design-system mismatch, migrate markers with /elementor/normalize and then use /elementor/update dry_run; do not bypass through /run.',
        ],
        'responsive_unit_policy' => [
            'required' => true,
            'rule' => 'Use responsive units wherever practical: rem/em for spacing, typography, gaps, padding, margins, radii, and component dimensions; vh/svh/min-height for viewport-height sections; percentages, flex basis, max-width, and responsive constraints for widths.',
            'px_exceptions' => [
                '1px borders and hairlines.',
                'Tiny icons and editor controls.',
                'Box shadows.',
                'Elementor controls that do not accept relative units reliably.',
            ],
            'preflight' => 'Structured Elementor writes warn when fixed px width/height settings are detected.',
        ],
        'native_style_settings_policy' => [
            'required' => true,
            'rule' => 'For every element style change, use native Elementor settings/style controls first. CSS is an exception, not the default.',
            'scope_boundary' => 'This rule applies to new styles and explicitly requested style changes. It is not permission to rewrite the whole page or remove working enhancement code.',
            'principle' => 'All styles Elementor supports natively must be set through widget/container native settings instead of external CSS.',
            'elementor_editor_editability_contract' => [
                'The owner must be able to edit design properties in Elementor after the agent finishes.',
                'If Elementor exposes a native control for a property, store that property in the element/container/widget settings in _elementor_data.',
                'Do not make CSS, an HTML widget, injected markup, an external file, or Custom CSS the only source of an editable design property.',
                'If a property from css_to_native_map appears in <script>-injected CSS, it is not editable in Elementor. The agent must migrate it to native settings and remove the injected CSS declaration.',
                'Do not remove native settings just because they generate page-specific CSS. Elementor-generated CSS from native settings is expected and editable.',
                'Only remove local native overrides when the user explicitly requests global Elementor style/design-token inheritance.',
                'When inheriting from global styles, document which properties were intentionally left unset and verify the global style is actually controlling them.',
            ],
            'css_to_native_map_contract' => 'Properties in this map must be set through native Elementor settings. They must not appear as the authoritative design source in Custom CSS, HTML widget CSS, external CSS files, or <script>-injected CSS.',
            'element_custom_css_policy' => [
                'editor_location' => 'Each Elementor widget/container can expose its own Custom CSS editor. In Elementor JSON, this control value is stored on that element as settings.custom_css.',
                'control_model' => 'Elementor controls save user data in element settings. Regular controls store one value; responsive controls store device-specific values; group and regular controls generate scoped CSS through selector/selectors definitions.',
                'editability' => 'settings.custom_css remains visible and editable inside the selected Elementor element. It is preferable to CSS hidden in an HTML widget, page-wide code, an external file, or JavaScript-injected <style>.',
                'scope' => 'Inside an element Custom CSS field, use Elementor selector to target that element wrapper, for example selector { ... }, selector::before { ... }, selector:hover { ... }, or selector .elementor-button { ... }. Do not use unscoped page-wide selectors there.',
                'priority' => 'A visual Style/Advanced control is still the first choice for every property Elementor supports. Use settings.custom_css only for behavior or styling the available controls cannot express cleanly.',
                'allowed_for' => [
                    'Pseudo-elements and decorative generated content.',
                    'Hover/focus states or transitions not exposed by the selected widget controls.',
                    'Keyframes and scoped animation polish.',
                    'Masks, browser fixes, advanced selectors, and complex responsive rules unavailable through Elementor controls.',
                    'WebGL/canvas support styles when they belong to the same protected enhancement element.',
                ],
                'forbidden_as_source_of_truth' => 'Do not put typography, colors, backgrounds, spacing, borders, radius, sizing, flex layout, positioning, or responsive values in settings.custom_css when the selected element exposes a corresponding Elementor control. Custom CSS must not override those controls with !important.',
                'preservation' => 'When changing an unrelated property, preserve existing settings.custom_css byte-for-byte. Patch only the requested element and declaration.',
                'safe_html_migration' => 'When moving one CSS fragment out of a large protected HTML/WebGL widget, use /elementor/patch op=replace_text with path=settings.html and exact expected_count instead of resending the complete HTML value.',
                'html_widget_fallback' => 'Do not create an HTML widget merely to hold CSS. Prefer the target element settings.custom_css. Keep HTML widgets for JavaScript, WebGL/canvas code, embeds, schema/meta, or enhancements that require markup/script.',
                'documentation' => [
                    'https://developers.elementor.com/docs/editor-controls/',
                    'https://developers.elementor.com/docs/editor-controls/using-controls/',
                    'https://developers.elementor.com/docs/editor-controls/responsive-control/',
                    'https://developers.elementor.com/docs/editor-controls/selectors/',
                    'https://developers.elementor.com/docs/editor-controls/control-code/',
                ],
            ],
            'css_to_native_map' => [
                'typography' => [
                    'font-family' => 'typography_font_family',
                    'font-size' => 'typography_font_size plus _mobile and _tablet responsive variants',
                    'font-weight' => 'typography_font_weight',
                    'line-height' => 'typography_line_height; use unitless ratio for multi-line headings/text',
                    'letter-spacing' => 'typography_letter_spacing',
                    'text-transform' => 'typography_text_transform',
                ],
                'colors' => [
                    'color' => 'title_color or text_color',
                    'background-color' => 'background_background plus background_color',
                    'linear/radial gradient' => 'background_background=gradient plus background_color, background_color_b, background_gradient_type, background_gradient_angle, and background_gradient_position where supported',
                    'background overlay gradient' => 'background_overlay_background=gradient plus background_overlay_color, background_overlay_color_b, and related overlay gradient settings where supported',
                    'border-color' => 'border_border plus border_color',
                ],
                'advanced_positioning' => [
                    'z-index' => '_z_index or z_index control/settings when Elementor exposes it for the element',
                    'position fixed/sticky' => 'Elementor Advanced/Positioning or Motion Effects sticky settings such as _position, sticky, sticky_on, sticky_offset, sticky_effects_offset, and sticky_parent when available',
                ],
                'spacing_and_size' => [
                    'padding' => 'padding for all needed breakpoints',
                    'margin' => 'margin',
                    'border-radius' => 'border_radius',
                    'min-height' => 'min_height',
                ],
                'flex_grid' => [
                    'display:flex' => 'flex_direction, justify_content, align_items',
                    'gap' => 'gap',
                    'flex-wrap' => 'flex_wrap',
                ],
            ],
            'native_first' => [
                'Backgrounds, text colors, button colors, borders, radii, spacing, width, min-height, flex layout, alignment, and responsive variants must be stored in element/container/widget settings when Elementor supports them.',
                'Normal and hover gradients supported by Elementor Group_Control_Background are native settings, not CSS exceptions.',
                'z-index and fixed/sticky positioning must use Elementor advanced/positioning/motion settings first when available.',
                'Typography for heading, text-editor, and button widgets must use typography_* settings, including responsive font-size variants when needed.',
                'Use unitless line-height for multi-line headings/text instead of px/em line-height.',
                'CSS may refine or reinforce a style, but it must not be the only source of essential background, contrast, spacing, border, typography, or layout.',
                'When CSS is used, scope it under page/project classes and keep the affected content editable through native widgets.',
            ],
            'preserve_existing_enhancements' => [
                'Do not delete, rewrite, simplify, or move existing scoped CSS, JavaScript, WebGL, Three.js, GSAP, canvas, shader, animation, or HTML widget enhancement code unless the user explicitly asks for that exact change.',
                'If an existing enhancement is working, preserve its widget, classes, IDs, script order, and dependency assumptions.',
                'Keep WebGL, Three.js, GSAP, canvas, shader, and complex animation code in a dedicated HTML widget or protected enhancement zone whenever possible.',
                'Do not merge protected enhancement code into a page-wide CSS/design HTML widget; keep enhancement code isolated so normal Elementor style edits do not risk breaking it.',
                'Native style migration must be targeted to the requested elements only; do not perform a page-wide restyle or cleanup pass.',
                'Before changing an existing page, compare before/after Elementor data and keep all unrelated HTML widget content byte-for-byte where possible.',
            ],
            'css_allowed_only_for' => [
                'Animations, transitions, hover/focus refinements, and progressive enhancement.',
                'Pseudo-elements such as ::before and ::after for decoration.',
                'WebGL/canvas styling.',
                'Gradients, masks, or patterns Elementor Group_Control_Background cannot express.',
                'position: fixed/sticky for global overlays or off-canvas UI when Elementor native positioning/sticky controls are insufficient.',
                'Custom systemic z-index layers when Elementor native z-index controls are insufficient.',
                '@import for Google Fonts.',
                'Media queries that Elementor responsive controls cannot express.',
                'Small JavaScript support styles.',
                'Complex responsive behavior that Elementor controls cannot express cleanly.',
                'Browser quirks or theme specificity conflicts after native settings are already present.',
                'Tiny visual details such as pseudo-elements, masks, advanced gradients, or decorative accents.',
            ],
            'script_injected_css_rule' => [
                'forbidden' => 'Never use <script>-injected <style> elements for properties in css_to_native_map.',
                'permitted_scope' => 'Script-injected CSS is allowed only for @import fonts, WebGL/canvas support, @keyframes, browser fixes, media queries, and properties without native Elementor equivalents.',
                'blocking_validation' => 'html_widget_script_injected_css blocks HTML widgets that inject style tags containing mapped native CSS properties.',
            ],
            'cache_rule' => [
                'After changing native settings, Elementor CSS cache must be cleared.',
                'Required cleanup: delete_post_meta(post_id, "_elementor_css") and delete_option("_elementor_global_css").',
                'If available, clear Elementor files cache and call rocket_clean_domain() for WP Rocket.',
                'If native settings do not appear publicly, suspect stale Elementor CSS cache before changing the settings again.',
            ],
            'css_forbidden_for' => [
                'Main page layout or content structure.',
                'Styles that Elementor has native controls for but the agent skipped.',
                'Global unscoped page-specific styles.',
                'Hiding missing native backgrounds, spacing, borders, typography, or contrast behind an HTML widget.',
                'Any property from css_to_native_map inside <script>-injected CSS.',
            ],
        ],
        'mobile_first_policy' => [
            'required' => true,
            'rule' => 'Start every page or new block from the mobile composition first, then progressively enhance tablet and desktop.',
            'elementor_requirements' => [
                'Set responsive Elementor controls for mobile stacking, wrapping, width, order, min-height, padding, gap, and alignment when a section is split, grid-like, or visually complex.',
                'Keep the main CTA visible and tappable on mobile without horizontal overflow.',
                'Use readable mobile typography and spacing from the design system before increasing desktop scale.',
                'Do not rely on desktop-only composition with mobile fixes added after the fact.',
            ],
            'verification' => [
                'Run /elementor/visual-audit before writing and treat weak mobile_readiness as a required fix.',
                'After writing, inspect the public page at mobile width first, then tablet/desktop.',
            ],
        ],
        'public_visual_audit_policy' => [
            'endpoint' => 'POST /wp-json/ai-executor/v1/visual-audit',
            'required_after_public_writes' => true,
            'scope' => 'Read-only public HTML checks for same-site post_id or url.',
            'checks' => [
                'public fetch status',
                'viewport/title/visible copy',
                'horizontal overflow risk from large fixed width/min-width styles',
                'invisible text patterns',
                'empty Elementor/WPAE blocks',
                'CTA presence',
                'mobile-first CSS signals',
            ],
            'limitations' => 'This endpoint intentionally avoids server-side screenshots and cannot compute true rendered overflow or full CSS cascade contrast.',
            'agent_rule' => 'Use /visual-audit after writes as a quick public-page sanity check, then use browser automation only on public pages for screenshots, clicks, rendered overflow, and contrast verification.',
        ],
        'elementor_preflight_policy' => [
            'applies_to' => [ 'POST /elementor/page', 'POST /elementor/update', 'changed _elementor_data after POST /run' ],
            'returned_as' => 'preflight',
            'blocks' => [
                'Invalid Elementor contract or design-system contract.',
                'Empty native heading/text widgets.',
                'HTML widget used as main layout/content.',
                'Landing page without a native button CTA.',
                'Landing page without native background, text color, padding, and gap settings.',
            ],
            'warns' => [
                'Fixed px width/height risks instead of responsive units.',
            ],
        ],
        'run_elementor_bypass_policy' => [
            'required' => true,
            'rule' => 'Agents must not use /run to bypass /elementor/update, design-system validation, dry_run, or Elementor preflight.',
            'enforcement' => 'Any _elementor_data changed after /run is validated with the same design-system and preflight contract. Failed writes are rolled back.',
            'allowed_run_use' => 'Use /run for small WordPress API tasks, cache clearing, diagnostics, or controlled metadata work that does not bypass structured Elementor endpoints.',
            'forbidden_run_use' => 'Do not directly update _elementor_data through /run to skip design-system marker classes, quality gates, dry_run, or structured endpoint validation.',
        ],
        'browser_admin_policy' => [
            'required' => true,
            'forbidden' => [
                'Requesting WP Admin login or password.',
                'Requesting admin cookies, WordPress REST nonces, browser sessions, or manual admin authentication.',
                'Using Playwright, browser automation, or WP Admin/Elementor editor to make content, style, meta, or settings changes.',
                'Treating 401/403 from WP Admin/browser nonce flows as a reason to ask for credentials.',
            ],
            'allowed' => [
                'Use WP AI Executor REST API with X-AI-Key for read endpoints.',
                'Use guide-token flow for write endpoints.',
                'Use Elementor structured endpoints for Elementor writes.',
                'Use browser automation only to inspect public, non-admin pages after API writes.',
            ],
            'rule' => 'If API auth fails, report the exact endpoint, headers used by name, HTTP status, and response body. Do not switch to WP Admin or request credentials.',
        ],
        'error_reporting_policy' => [
            'required' => true,
            'rule' => 'If any endpoint, validation, preflight, write, cache clear, or verification step fails, the agent must include concrete error details in its response.',
            'must_include' => [
                'Endpoint or action name.',
                'HTTP status or exception type when available.',
                'Plugin error code/message and details/preflight/blocking_errors when returned.',
                'The attempted fix or next safe step.',
            ],
            'forbidden' => 'Do not hide failures behind vague summaries such as "there was an issue" or claim completion while errors remain unresolved.',
        ],
        'after_save_quality_summary_policy' => [
            'applies_to' => [ 'POST /elementor/page', 'POST /elementor/update' ],
            'returned_as' => 'quality_summary',
            'contains' => [
                'permalink and post status.',
                'visual audit score and level.',
                'preflight warnings and blocking status.',
                'concrete fixes the agent should apply before claiming completion.',
            ],
            'rule' => 'If quality_summary.visual_audit.level is weak/blocked or fixes are present, the agent must continue correcting the page before reporting completion.',
        ],
        'transaction_write_policy' => [
            'applies_to' => [ 'POST /elementor/page', 'POST /elementor/update', 'POST /elementor/patch' ],
            'mode' => 'atomic',
            'returned_as' => 'transaction',
            'rule' => 'Structured Elementor writes create a rollback snapshot before writing, verify saved metadata and cache refresh after writing, and automatically roll back on transaction failure.',
            'auto_rollback_on' => [
                'metadata save error.',
                'saved _elementor_data is missing, invalid JSON, or fails Elementor validation.',
                'saved data violates the active design-system contract.',
                'Elementor CSS cache clear reports an error.',
                'public verification fails when transaction_verify_public=true.',
                'visual regression comparison fails when transaction_visual_regression=true.',
                'static quality is weak/blocked when transaction_strict_quality=true.',
            ],
            'optional_request_flags' => [
                'transaction_verify_public=true fetches the public permalink after save and runs /visual-audit style checks; failure triggers rollback.',
                'transaction_visual_regression=true captures a public HTML/audit baseline before existing-page writes and compares status, visible text, CTA, overflow, empty blocks, and audit level after save; failure triggers rollback.',
                'transaction_strict_quality=true treats weak/blocked static visual audit as a transaction failure.',
            ],
            'failure_rule' => 'If transaction.ok=false, read transaction.failed_checks and transaction.auto_rollback. Do not retry through /run, WP Admin, browser writes, or direct metadata edits. Fix the payload and repeat dry_run first.',
        ],
        'elementor_patch_policy' => [
            'endpoint' => 'POST /wp-json/ai-executor/v1/elementor/patch',
            'preferred_for' => 'Small targeted native Elementor settings changes by element_id, such as typography, colors, spacing, gap, alignment, min-height, border, radius, links, and widget content.',
            'rule' => 'Use /elementor/patch instead of rebuilding the whole page when only specific element settings need to change.',
            'payload_shape' => [
                'post_id' => 123,
                'dry_run' => true,
                'patches' => [
                    [
                        'element_id' => 'hero_title',
                        'path' => 'settings.typography_font_size',
                        'op' => 'set',
                        'value' => [ 'unit' => 'rem', 'size' => 4.5 ],
                    ],
                    [
                        'element_id' => 'hero_title',
                        'path' => 'settings.title_color',
                        'op' => 'set',
                        'value' => '#111827',
                    ],
                ],
            ],
            'allowed_paths' => [
                'settings.*',
                'elements.{index}.settings.* for tightly scoped nested settings only',
            ],
            'blocked_paths' => [
                'elType',
                'widgetType',
                'id',
                'arbitrary structural rewrites',
            ],
            'validation' => 'Patch output runs the same Elementor validation, design-system contract, preflight, atomic transaction, cache refresh, and rollback path as /elementor/update.',
        ],
        'protected_enhancement_zones_policy' => [
            'required' => true,
            'purpose' => 'Prevent native-style migrations and targeted edits from breaking working WebGL, Three.js, GSAP, canvas, shader, or HTML enhancement blocks.',
            'how_to_mark' => 'Add the wpae-protected-zone class to the owning Elementor element or data-wpae-protected to its HTML. HTML widgets with enhancement keywords are also protected automatically.',
            'enforcement' => 'On existing pages, /elementor/page updates, /elementor/update, and /elementor/patch block removal or byte-level modification of protected zones by default.',
            'override' => 'Only change a protected zone when the task explicitly requires it. Send allow_protected_zone_changes=true and a concrete protected_zone_reason of at least 10 characters, then verify the public animation after write.',
            'agent_rule' => 'Do not use an override for unrelated typography, spacing, or layout work. Preserve the protected widget, its IDs/classes, script order, and dependencies byte-for-byte.',
        ],
        'repeated_agent_error_audit_policy' => [
            'returned_in' => [ 'POST /elementor/visual-audit', 'POST /audit' ],
            'rule' => 'Agents must read repeated_agent_error_audit and fix every fail check before claiming success; warn checks must be either fixed or explicitly explained.',
            'checks' => [
                'legacy_sections_columns',
                'snake_case_widget_type',
                'html_widget_layout_or_content',
                'script_injected_native_css',
                'heading_typography_important_override',
                'excessive_local_typography_overrides',
                'design_system_marker_drift',
                'fixed_px_layout_risk',
            ],
        ],
        'runtime_elementor_validation' => [
            'required' => true,
                'rule' => 'The executor validates changed _elementor_data after each /run call and rejects invalid Elementor JSON, missing design-system markers, and failed preflight even if the agent ignored the guide.',
                'normalize_endpoint' => [
                    'endpoint' => 'POST /wp-json/ai-executor/v1/elementor/normalize',
                    'writes' => false,
                    'rule' => 'Use this before saving when JSON has legacy section/column layout, widget_type, missing widgetType, missing settings arrays, missing elements arrays, or incomplete container defaults.',
                    'returns' => [
                        'normalized_elementor_data',
                        'change_counts',
                        'changes',
                        'before_errors',
                        'after_errors',
                        'stats',
                    ],
                ],
                'blocked' => [
                    'Legacy elType=section.',
                    'Legacy elType=column.',
                    'Snake-case widget_type.',
                    'Any elType=widget element with missing or empty widgetType.',
                ],
                'rollback' => 'If invalid _elementor_data is detected, the changed _elementor_data meta is rolled back to its pre-run value when possible.',
            ],
            'blueprint_policy' => [
                'endpoint' => 'POST /wp-json/ai-executor/v1/elementor/blueprint',
                'writes' => false,
                'rule' => 'Before building a new Elementor page, call /elementor/blueprint with subject, audience, goal, offer, language, style, proof_points, and CTA labels.',
                'returns' => [
                    'design_tokens',
                    'section plan',
                    'recipe IDs and variants',
                    'slot suggestions',
                    'native widget requirements',
                    'HTML enhancement zones',
                    'design quality gates',
                    'agent workflow',
                ],
                'usage' => [
                    'Treat the blueprint as the page contract.',
                    'Use recipes when recipe_available=true.',
                    'For custom sections, use native Flexbox Container primitives and then normalize/validate.',
                    'Do not write a page until the intended sections map back to the blueprint.',
                ],
            ],
            'recipes_policy' => [
                'list_endpoint' => 'GET /wp-json/ai-executor/v1/elementor/recipes',
                'recipe_endpoint' => 'GET /wp-json/ai-executor/v1/elementor/recipes/{id}',
                'compose_endpoint' => 'POST /wp-json/ai-executor/v1/elementor/compose',
                'writes' => false,
                'rule' => 'Recipes are composition patterns, not rigid templates. Use variants and slots to build complex native Elementor sections while preserving editor usability.',
                'available_sections' => [
                    'hero.editorial',
                    'feature.grid',
                    'process.steps',
                    'pricing.comparison',
                    'faq.accordion',
                    'cta.band',
                    'proof.timeline',
                    'contact.block',
                ],
                'available_primitives' => [
                    'container.stack',
                    'container.grid',
                    'container.split',
                    'widget.heading',
                    'widget.copy',
                    'widget.cta-row',
                    'widget.metric',
                    'widget.feature-item',
                    'widget.html-enhancement',
                ],
                'workflow' => [
                    'Call /elementor/recipes to inspect available patterns.',
                    'Call /elementor/recipes/{id} to inspect slots and variants.',
                    'Call /elementor/compose with recipe_id, variant, and slots.',
                    'Run /elementor/normalize and /elementor/validate on the returned elementor_data before saving.',
                ],
                'constraints' => [
                    'Layout must remain native Flexbox Containers.',
                    'Main content must remain native editable widgets.',
                    'HTML widgets are allowed only as scoped enhancement zones, not main layout.',
                    'All required slots should be filled with project-specific content.',
                ],
            ],
            'rollback_policy' => [
                'endpoint' => 'POST /wp-json/ai-executor/v1/rollback',
                'storage' => 'Short-lived snapshots are stored in wp_options, never in files.',
                'ttl_seconds' => WPAE_ROLLBACK_TTL_SECONDS,
                'rule' => 'For structured Elementor writes, read rollback_snapshot_id and rollback_expires_at from the response. To revert, call /rollback with the snapshot_id and valid guide-token headers. Rollback validates _elementor_data before replacing metadata; if it fails, the snapshot is retained and the agent must stop, report the endpoint/status/error details, and never bypass recovery through /run, WP Admin, or browser automation.',
                'dry_run' => [
                    '/elementor/page' => 'Pass dry_run=true to validate the requested create/update without writing.',
                    '/elementor/update' => 'Pass dry_run=true to validate the requested metadata update without writing.',
                    '/elementor/patch' => 'Pass dry_run=true to validate targeted element_id/property changes without writing.',
                    '/run' => 'Arbitrary PHP dry_run is not supported because the plugin cannot reliably simulate unknown mutations. Use rollback_targets instead.',
                ],
                'run_rollback_targets' => [
                    'body' => [
                        'code' => 'return update_option("example_option", "new-value");',
                        'rollback_targets' => [
                            'post_ids' => [ 123 ],
                            'option_names' => [ 'example_option' ],
                        ],
                    ],
                    'rule' => 'Before risky /run mutations, pass known post_ids and option_names so the plugin captures a rollback snapshot first.',
                ],
            ],
            'operation_logs_policy' => [
                'endpoint' => 'GET /wp-json/ai-executor/v1/logs',
                'storage' => 'Recent operation metadata is stored in wp_options with a capped entry count.',
                'max_entries' => WPAE_OPERATION_LOG_MAX_ENTRIES,
                'logged' => [
                    'endpoint',
                    'method',
                    'status',
                    'duration_ms',
                    'actor hint',
                    'guide hash',
                    'target IDs',
                    'rollback snapshot ID',
                    'validation summary',
                ],
                'redacted' => [
                    'API keys',
                    'guide tokens',
                    'raw request bodies',
                    'raw page payloads',
                    'raw response payloads',
                    'secrets',
                ],
            ],
            'elementor_visual_audit' => [
                'endpoint' => 'POST /wp-json/ai-executor/v1/elementor/visual-audit',
                'input' => 'Pass post_id for a saved page or elementor_data to audit before writing.',
                'rule' => 'After composing or writing a page, run visual-audit and fix weak/blocked results before claiming completion.',
                'checks' => [
                    'runtime_elementor_contract' => 'Flexbox Container contract, widgetType, and validation errors.',
                    'native_background_coverage' => 'Important backgrounds are present in native Elementor settings.',
                    'native_text_color_coverage' => 'Readable text colors are not only inherited or CSS-only.',
                    'native_spacing_coverage' => 'Container padding/gap are present as native settings.',
                    'typography_hierarchy' => 'Native heading hierarchy exists.',
                    'native_cta' => 'A native button CTA exists and is styled.',
                    'responsive_settings' => 'Mobile/tablet settings exist for complex layouts.',
                    'html_widget_scope' => 'HTML widgets are enhancement-only.',
                    'native_content_complete' => 'No empty heading/text widgets.',
                    'palette_variety' => 'Palette variety is detectable from native settings.',
                ],
            ],
            'public_visual_audit' => [
                'endpoint' => 'POST /wp-json/ai-executor/v1/visual-audit',
                'input' => 'Pass post_id or same-site url after a page is public.',
                'rule' => 'Run the read-only public HTML audit after writes and report/fix weak or blocked results before claiming completion.',
                'checks' => [
                    'public_fetch' => 'The permalink is reachable without WP Admin authentication.',
                    'html_structure' => 'Viewport meta, title, and visible copy are present.',
                    'horizontal_overflow_risk' => 'Large fixed width/min-width styles are flagged.',
                    'invisible_text_risk' => 'Hidden or transparent text patterns are flagged.',
                    'empty_block_risk' => 'Suspicious empty Elementor/WPAE blocks are flagged.',
                    'cta_presence' => 'A public link/button CTA is detectable.',
                    'mobile_first_css_signal' => 'Mobile responsive CSS signals are visible.',
                ],
                'limitations' => 'No screenshots, true rendered overflow, computed contrast cascade, or animation timing.',
            ],
            'agent_conformance_policy' => [
                'returned_in_responses' => true,
                'included_in_logs' => true,
                'rule' => 'Every scored endpoint returns agent_conformance with score, level, criteria, and blocking_errors. A weak or blocked level means the agent should correct the operation or run verification before claiming success.',
                'criteria' => [
                    'guide_token_flow' => 'Write endpoints should use the required guide token and guide hash.',
                    'file_policy' => 'No forbidden filesystem operations or scratch files.',
                    'elementor_policy' => 'Elementor data passes runtime validation.',
                    'native_flex_containers' => 'Elementor layout uses Flexbox Containers and no legacy section/column layout.',
                    'widget_type_integrity' => 'Widgets use camelCase widgetType and never widget_type.',
                    'native_visual_settings' => 'Critical visual state is present in native Elementor settings where detectable.',
                    'typography_hierarchy' => 'Native heading widgets create a real visual/content hierarchy.',
                    'spacing_consistency' => 'Native container padding and gaps are used consistently.',
                    'cta_visibility' => 'A native Elementor button exists for the primary action.',
                    'mobile_readiness' => 'Responsive Elementor settings are present for complex sections.',
                    'palette_quality' => 'The palette has enough variety without becoming noisy.',
                    'content_completeness' => 'Native heading/text widgets are populated and not placeholder-empty.',
                    'verification_signal' => 'Use /audit or X-WPAE-Verified: 1 after writes.',
                ],
                'design_quality_bar' => [
                    'Treat weak typography hierarchy, missing CTA, sparse native spacing, missing responsive settings, or empty content as unfinished work.',
                    'Prefer fixing native Elementor settings first; scoped CSS may reinforce but should not hide missing editor settings.',
                    'If a complex section cannot fit an existing recipe, compose from native container/widget primitives and validate with /elementor/normalize and /elementor/validate.',
                ],
            ],
            'native_elementor_first' => [
                'required' => true,
                'rule' => 'Build page structure and content from native Elementor Flexbox Containers and widgets so the user can edit content and styling in the Elementor editor panel. Use elType=container for all layout nodes.',
                'layout_system' => [
                    'required' => 'Elementor Flexbox Containers only.',
                    'allowed_layout_eltypes' => [
                        'container',
                    ],
                    'forbidden_legacy_eltypes' => [
                        'section',
                        'column',
                    ],
                    'rule' => 'Do not create, import, or preserve legacy Section/Column layouts. Convert every layout wrapper to nested containers with flex_direction, content_width, width, gap, padding, and responsive settings.',
                ],
                'allowed_widget_types' => [
                    'heading',
                    'text-editor',
                    'button',
                    'icon-list',
                    'image',
                    'image-box',
                    'icon-box',
                    'divider',
                    'spacer',
                    'counter',
                    'progress',
                    'testimonial',
                    'tabs',
                    'accordion',
                    'toggle',
                ],
                'forbidden_widget_types' => [
                    'shortcode',
                ],
                'conditional_widget_types' => [
                    'html' => 'Allowed only for small JavaScript snippets or complex CSS enhancements that cannot reasonably be expressed with native Elementor settings. Never use it as the main page markup/content/layout container.',
                ],
                'native_style_settings' => [
                    'required' => true,
                    'rule' => 'Element style changes must be made in native Elementor settings/style controls first.',
                    'typography_editability_rule' => 'Native typography does not mean every widget must receive explicit typography_* values. Repeated local typography_font_family, typography_font_size, typography_font_weight, typography_line_height, typography_letter_spacing, typography_text_transform, typography_font_style, typography_text_decoration, or typography_word_spacing settings block global typography edits. Use local typography only where the design intentionally needs a one-off exception.',
                    'unlock_endpoint' => 'If a page already has excessive local typography overrides, use POST /wp-json/ai-executor/v1/elementor/typography-unlock with dry_run=true first, then apply it with preserve_ids/preserve_classes for intentional exceptions.',
                    'override_resolution_endpoint' => 'If an HTML widget CSS rule uses !important to override native heading typography, use POST /wp-json/ai-executor/v1/elementor/resolve-typography-overrides with dry_run=true and explicit native_typography_patches. It only relaxes typography !important tokens on heading selectors and preserves the rest of the HTML widget.',
                    'examples' => [
                        'Use background_color/background_background for section and card backgrounds.',
                        'Use title_color/text_color/button color controls for readable text and CTA contrast.',
                        'Use border, radius, padding, margin, gap, width, min-height, flex direction, wrap, justify, align, and responsive controls for layout and spacing.',
                        'Use _css_classes only to attach scoped enhancements after native settings are present.',
                    ],
                    'css_exception' => 'Use CSS only when a native setting cannot express the requested behavior or when refining an already native-styled element.',
                ],
                'content_placement' => [
                    'Headlines must live in heading widget settings.title.',
                    'Body copy must live in text-editor widget settings.editor.',
                    'Calls to action must live in button widget settings.text and settings.link.',
                    'Lists must live in icon-list repeater settings when practical.',
                    'Cards, columns, grids, hero panels, and sections must be Flexbox Containers with settings and child widgets.',
                    'Critical visual state required for readability must live in native Elementor settings first: background_color, text color, border, border_radius, padding, margin, width, min-height, gap, and alignment.',
                ],
                'forbidden_patterns' => [
                    'Do not create temporary loader files, mu-plugins, helper PHP files, external CSS/JS files, JSON/base64 payload files, or scratch files anywhere on the server.',
                    'Do not use legacy Elementor sections or columns: elType=section and elType=column are forbidden.',
                    'Do not put full page markup into an Elementor HTML widget.',
                    'Do not use inline CSS/JS blobs to fake the main page structure.',
                    'Do not replace editable Elementor controls with opaque HTML.',
                    'Do not use CSS as the default way to change element styling when Elementor has native style controls.',
                    'Do not use CSS-only critical backgrounds, contrast, spacing, borders, or typography when native settings can express them.',
                    'Do not rely on enhancement CSS as the only source for essential backgrounds, contrast, spacing, or card borders.',
                ],
                'verification' => [
                    'Confirm the solution did not create or require any external files.',
                    'Traverse _elementor_data recursively.',
                    'Confirm all layout elements are elType=container and all content elements are allowed native widgets.',
                    'Confirm there are zero elements with elType=section or elType=column.',
                    'If html widgets exist, confirm each one is limited to JS or complex CSS enhancements, not page content/layout.',
                    'Confirm important text lives in heading/text-editor/button/icon-list settings.',
                    'Confirm each changed element style exists in native Elementor settings first, with CSS only as an explained exception.',
                    'Confirm unrelated existing CSS/JS/WebGL/Three.js/GSAP/animation enhancements were preserved.',
                    'Confirm any visually critical card, panel, hero, or dark section has native Elementor background and border settings before relying on CSS.',
                ],
            ],
            'html_enhancement_policy' => [
                'allowed' => true,
                'rule' => 'HTML widget CSS/JS/WebGL is exceptional enhancement only and may be edited only when the requested change concerns that enhancement. If Elementor has a native control for the style, set the native control first, but preserve existing working enhancements unless the user explicitly asks to change them.',
                'allowed_for' => [
                    'Google Fonts or other font loading when the site has no better typography pipeline.',
                    'Scoped CSS polish for classed Elementor containers/widgets.',
                    'Small JavaScript interactions such as scroll reveal, hover helpers, tabs state, counters, or progressive enhancement.',
                    'Complex responsive CSS that Elementor settings cannot express cleanly.',
                    'WebGL, Three.js, GSAP, canvas, shader, or animation enhancements that cannot be represented as native Elementor settings.',
                ],
                'requirements' => [
                    'For CSS-only enhancement, use the target widget/container settings.custom_css with Elementor selector before considering an HTML widget.',
                    'Use a separate dedicated HTML widget for WebGL, Three.js, GSAP, canvas, shader, or complex animation code whenever possible.',
                    'Do not combine WebGL/animation code with page-wide design CSS in the same HTML widget.',
                    'Do not modify, delete, merge, or relocate an existing WebGL/Three.js/GSAP/canvas HTML widget unless the user explicitly asks to change that enhancement.',
                    'Scope CSS under project-specific classes, e.g. .wpae-* or page-specific .mz-*.',
                    'Do not target .elementor-widget-container as the primary selector.',
                    'Never inject <style> with JavaScript for properties that Elementor can edit natively; this is blocked by html_widget_script_injected_css validation.',
                    'Use !important only as an enhancement fallback for scoped selectors when Elementor/theme CSS wins specificity.',
                    'Do not use !important to compensate for missing native Elementor settings on critical backgrounds, colors, borders, spacing, or layout.',
                    'When CSS is used, state why native Elementor settings were insufficient.',
                    'When an existing HTML widget contains CSS/JS/WebGL/Three.js/GSAP/canvas code unrelated to the requested change, preserve it unchanged.',
                    'Respect prefers-reduced-motion for animation.',
                    'Use vanilla JavaScript in an IIFE; avoid jQuery unless WordPress/Elementor dependency forces it.',
                    'HTML widget must be enhancement-only and removable without losing the page content.',
                ],
            ],
            'page_meta' => [
                '_elementor_edit_mode' => 'builder',
                '_elementor_template_type' => 'wp-page',
                '_elementor_version' => 'Use ELEMENTOR_VERSION when defined.',
                '_elementor_data' => 'JSON-encoded Elementor element array, stored with wp_slash().',
                '_wp_page_template' => 'elementor_canvas for full landing pages when appropriate.',
            ],
            'element_shape' => [
                'container' => [
                    'id' => 'unique 7-8 character string',
                    'elType' => 'container',
                    'isInner' => false,
                    'settings' => 'Container/Flexbox settings.',
                    'elements' => 'Nested widgets or containers.',
                ],
                'widget' => [
                    'id' => 'unique 7-8 character string',
                    'elType' => 'widget',
                    'widgetType' => 'Required camelCase key. Native editable Elementor widget, e.g. heading, text-editor, button, icon-list, image, divider, spacer. HTML widget is allowed only for JS or complex CSS enhancements, never for main layout/content.',
                    'isInner' => false,
                    'settings' => 'Widget control values.',
                    'elements' => [],
                ],
            ],
            'elementor_data_rules' => [
                'Use recursive arrays of containers and widgets.',
                'Every element needs id, elType, isInner, settings, and elements.',
                'Every widget element must use the exact camelCase key widgetType. Never use widget_type, widget_type_name, type, or name as substitutes.',
                'If elType is widget and widgetType is missing or empty, Elementor will render an empty/broken widget; treat this as a blocker.',
                'Never emit legacy elType=section or elType=column. If source data contains them, convert to nested elType=container before saving.',
                'Use Flexbox Container settings for layout: flex_direction, content_width, width, min_height, gap, padding, margin, justify_content, align_items, flex_wrap, and responsive variants.',
                'Use rem/em where practical for gap, padding, margin, typography, radii, and component dimensions; use vh/svh/min-height for viewport sections and percentages/flex/max-width for widths.',
                'Use deterministic short ids when possible so future updates can target stable elements.',
                'Use _css_classes in settings to attach scoped enhancement styles.',
                'For readable sections and cards, duplicate essential styling in settings before adding CSS: background_background, background_color, title/text colors, border_border, border_color, border_width, border_radius, padding, margin, gap, width, min-height, and alignment.',
                'Clear/regenerate Elementor CSS cache after writing page data when Elementor classes are available.',
            ],
            'verification_checklist' => [
                'HTTP status for permalink is 200.',
                'Post status is publish unless the user requested draft.',
                '_wp_page_template is elementor_canvas for full landing pages when appropriate.',
                '_elementor_edit_mode is builder.',
                '_elementor_data decodes as JSON array.',
                '_elementor_data contains no legacy section or column elements.',
                'Every elType=widget element has non-empty widgetType and no widget_type key.',
                'Core text is stored in native widget settings, not opaque HTML.',
                'Any html widget is enhancement-only.',
                'Critical backgrounds, borders, spacing, and contrast are present in native Elementor settings, with CSS only refining or reinforcing them.',
                'Changed element styles are stored in native Elementor settings first; CSS usage is scoped and justified as an exception.',
                '/visual-audit passes or returns only explained warnings.',
                'No external files, temporary loaders, mu-plugins, scratch files, or filesystem writes were created or required.',
                'Desktop and mobile layout should not have obvious overlap or horizontal overflow.',
            ],
            'php_snippet' => wpae_elementor_page_snippet(),
        ],
        'security' => [
            'Treat X-AI-Key as sensitive WordPress automation access, restricted by site-owner capability toggles and guide-token flow.',
            'Use X-AI-Key as the only canonical API-key header. X-WPAE-API-Key is accepted only as a deprecated backwards-compatible alias and responses include an auth warning when it is used.',
            'Never ask for or use WP Admin login/password, admin cookies, REST nonces, or browser sessions.',
            'Never commit, log, or expose real keys in frontend code.',
            'Never create temporary loaders, mu-plugins, PHP/JS/CSS/JSON/base64 files, or scratch files on the server.',
            'Never use Playwright, WP Admin, or the Elementor editor to make writes; use browser automation only for public-page verification after REST API writes.',
            'Filesystem write/delete operations are blocked by default in /run; do not ask agents to bypass this.',
            'Prefer server/firewall IP restrictions for production.',
            'Run read-only checks before writes and verify after writes.',
        ],
    ];
}

function wpae_agent_prompt(): string {
    return <<<'PROMPT'
You are operating a remote WordPress site through WP AI Executor.
Current runtime notes: rollback restores only plugin-managed Elementor/WPAE meta plus the post record and does not remove unrelated third-party post meta; /elementor/page attempts to delete a newly created page if Elementor metadata saving fails and reports cleanup.created_post_deleted; /media/upload rejects files whose binary signature does not match mime_type; /exports/create stores short-lived JSON in wp_options and returns an authenticated /exports/{id} endpoint, never a public uploads file; use GET /exports for metadata and POST /exports/prune to remove expired export records.
CSS-to-native migration note: when editable Elementor-supported styles are trapped in HTML widget <style> blocks, call /elementor/css-to-native with dry_run=true first, review report.migrated_declarations and editability_audit, then save only if it preserves protected zones and removes only mapped declarations. Typography editability note: if the user should control typography globally or through Elementor design roles, do not hardcode typography_* settings on every widget; repeated local typography overrides block global edits. Use /elementor/typography-unlock with dry_run=true to remove excessive local typography overrides while preserving intentional exceptions. If an HTML widget CSS selector with !important is blocking a native heading control, do not delete or rewrite the HTML widget: call /elementor/resolve-typography-overrides with dry_run=true and explicit native_typography_patches, then verify the returned report before saving.
Custom HTML note: Custom HTML is allowed and editable for JavaScript, WebGL/canvas, Three.js, GSAP, embeds, schema/meta, and CSS that has no native Elementor equivalent. Keep WebGL/Three.js/GSAP/canvas/shader/animation code in a separate dedicated HTML widget or protected enhancement zone whenever possible, and do not modify, delete, merge, or relocate that widget unless the user explicitly asks to change the enhancement. Never use Custom HTML as a workaround for Elementor-editable typography, colors, backgrounds, spacing, borders, radius, flex layout, sizing, or responsive values.
Element Custom CSS note: every widget/container can keep scoped CSS in its own Elementor Custom CSS control as settings.custom_css. For CSS-only exceptions, prefer that field over HTML widget CSS, page-wide CSS, external files, or JavaScript-injected style tags. Use Elementor selector to scope the current element: selector { ... }, selector::before { ... }, selector:hover { ... }, or selector .child { ... }. Standard typography, color, background, spacing, border, size, layout, positioning, and responsive values still belong in their visual Elementor controls whenever those controls exist. Preserve unrelated settings.custom_css byte-for-byte.
Elementor editor editability note: design properties must stay editable through native Elementor controls/settings. Do not move editable properties into CSS/HTML, and do not remove native settings unless the user explicitly asks for global inheritance from Elementor styles/design tokens.
Before writing, fetch and follow this guide as the source of truth. Inspect the environment first. Use X-AI-Key as the canonical API-key header; X-WPAE-API-Key is only a deprecated backwards-compatible alias and any response warning about it means you must switch back to X-AI-Key. Read /capabilities and respect site-owner capability toggles; a disabled capability is a hard stop even with a valid key. Read every enabled custom_skills item in this guide before any WordPress/Elementor work and apply those skills as mandatory project rules by priority; if a skill conflicts with WP AI Executor policy, WP AI Executor policy wins. Apply embedded jezweb_claude_skills where relevant for WordPress/Elementor, landing pages, design review, color palettes, responsiveness, and production verification, but WP AI Executor rules override upstream instructions whenever they conflict. Before creating a page or adding a new page block, call /elementor/design-system and treat its system_id, required_root_classes, palette, typography roles, spacing, radii, button style, and tone as the single style source for all current and future blocks. Design mobile first: plan the mobile stack, type scale, spacing, CTA visibility, tap targets, section order, and responsive Elementor settings before expanding tablet and desktop layouts. All top-level page/block containers must include the returned required_root_classes in settings._css_classes; /elementor/page and /elementor/update reject writes that miss this contract. Read project_design_tokens from the guide and use them as the site visual system. Write endpoints require a guide token: call /guide/session, read /guide and /capabilities, call /guide/ack, then send X-WPAE-Guide-Token and X-WPAE-Guide-Hash with every write request. Never request or use WP Admin login/password, admin cookies, WordPress REST nonces, or browser sessions; if auth fails, report endpoint/status/body and verify X-AI-Key instead of asking for credentials. Never use Playwright, WP Admin, or Elementor editor to write changes; browser automation is allowed only to inspect public pages after REST API writes. Never create external files on the WordPress server: no temporary loaders, mu-plugins, helper PHP files, CSS/JS/JSON/base64 payload files, scratch files, or files in /tmp. Use WordPress APIs and Elementor metadata only; /run blocks common filesystem write/delete operations by default. Prefer /elementor/design-system, /elementor/blueprint, /elementor/recipes, /elementor/compose, /elementor/normalize, /elementor/validate, /elementor/visual-audit, /elementor/typography-unlock, /visual-audit, /elementor/page, and /elementor/update over raw PHP for Elementor pages. Never use /run to bypass /elementor/update, design-system marker classes, dry_run, or Elementor preflight; direct _elementor_data changes through /run are validated by the same design-system/preflight contract and rolled back on failure. If an existing page has old or different wpae-system-* marker classes, migrate it to the current main design system with /elementor/normalize, preserve non-WPAE custom classes, then run /elementor/update dry_run. Before building a new page, call /elementor/blueprint with subject, audience, goal, offer, language, style, proof points, and CTA labels. For complex or non-standard sections, call /elementor/recipes, choose a recipe/variant, then call /elementor/compose with project-specific slots. Use /elementor/normalize before saving when JSON has legacy section/column layout, widget_type, missing widgetType, missing settings, missing elements arrays, incomplete container defaults, or missing design-system marker classes. Use /elementor/visual-audit and /elementor/editability-audit on composed elementor_data before writing and on post_id after writing; use /elementor/css-to-native dry_run=true before manually rewriting CSS that maps to native Elementor controls; use /visual-audit on the public page after writing; fix weak mobile_readiness, public HTML warnings, or other blocked audit results before claiming completion. Use dry_run=true on /elementor/page or /elementor/update before complex writes; use transaction_visual_regression=true when updating an existing public page where accidental visual breakage would matter; structured writes return preflight and block invalid contracts, empty native content, HTML-widget layout misuse, missing landing-page CTA, and missing native critical visual settings. Successful structured writes return quality_summary with permalink, visual audit score/level, warnings, and fixes; keep correcting until quality_summary has no required fixes and the audit is acceptable. Arbitrary /run dry_run is not supported, so pass rollback_targets.post_ids and rollback_targets.option_names before risky /run mutations. Save rollback_snapshot_id from write responses and call /rollback with snapshot_id if the result must be reverted. For Elementor pages, design first: define subject, audience, single page job, palette, type roles, mobile-first layout, and one distinctive signature element inside the design system. Apply the embedded frontend_design pack to avoid generic pages, apply the wordpress_elementor_dev pack to build editable Elementor output, and apply the jezweb landing-page/design-review/color-palette workflow to produce tangible, polished results. Use only native Elementor Flexbox Containers for layout: elType=container plus editable native widgets. Never use legacy Elementor Sections or Columns; elType=section and elType=column are forbidden and must be converted to containers before saving. Every widget must use the exact camelCase widgetType key; widget_type is forbidden and causes empty widgets. Put all Elementor-supported styles into native settings/style controls: typography_font_family, typography_font_size plus mobile/tablet variants, typography_font_weight, typography_line_height with unitless ratio for multi-line text, typography_letter_spacing, typography_text_transform, title_color/text_color, background_background/background_color/background_color_b/background_gradient_type/background_gradient_angle/background_gradient_position, background_overlay_background/background_overlay_color/background_overlay_color_b, border_border/border_color, padding, margin, border_radius, min_height, flex_direction, justify_content, align_items, gap, flex_wrap, native z-index controls (_z_index/z_index), and native Elementor positioning/sticky controls (_position/sticky/sticky_on/sticky_offset/sticky_effects_offset/sticky_parent) when available. Elementor-generated CSS from native settings is expected and editable in the Elementor panel; do not treat it as forbidden external CSS. Properties listed in css_to_native_map must not be authored through Custom CSS, HTML widget CSS, external files, or <script>-injected <style>; if they appear there, migrate the value to native Elementor settings and remove the CSS declaration. CSS is an exception only for animations, pseudo-elements, WebGL/canvas, gradients/patterns that Elementor Group_Control_Background cannot express, fixed/sticky global overlays or off-canvas UI when native positioning controls are insufficient, custom systemic z-index layers when native z-index controls are insufficient, Google Fonts @import, media queries Elementor cannot express, hover/focus polish, browser fixes, or specificity conflicts after native settings are present; scoped CSS, including selective !important, may reinforce or refine styles but must not be the default styling method or the only source of essential contrast or layout. Native style migration must be targeted to requested elements only: do not rewrite the whole page, do not remove working scoped CSS/JS/WebGL/Three.js/GSAP/canvas/shader/animation code, and preserve unrelated HTML widget content, classes, IDs, script order, and dependencies unless the user explicitly asks to change them. Prefer rem/em for spacing, typography, gap, padding, margin, radii, and component dimensions; use vh/svh/min-height for viewport-height sections; use percentages, flex basis, max-width, and responsive constraints for widths. Use px only for hairline borders, tiny icons/controls, shadows, or Elementor compatibility exceptions. After changing native settings, clear Elementor CSS cache: delete_post_meta(post_id, "_elementor_css"), delete_option("_elementor_global_css"), Elementor files cache when available, and rocket_clean_domain() when WP Rocket exists. The Elementor HTML widget is allowed only for small JavaScript snippets, WebGL/canvas/animation code, embeds, schema/meta, or complex CSS enhancements when native settings are not enough; never use it as the main page markup/content/layout container. Keep WebGL, Three.js, GSAP, canvas, shader, and complex animation code in a separate dedicated HTML widget or protected enhancement zone whenever possible, and do not modify, delete, merge, or relocate that widget unless the user explicitly asks to change the enhancement. Never inject <style> via JavaScript for native Elementor properties; html_widget_script_injected_css is a blocking validation error. Do not use shortcode widgets, Oxygen, or Novamira for page layout/content. After writing, rollback, typography migration, or revision restore, run /audit, /elementor/visual-audit, /elementor/editability-audit, /visual-audit, and real browser screenshot verification of the public URL; HTML/CSS audits alone are not enough. Then complete the verification checklist: published URL, Elementor meta, decoded _elementor_data, public HTML audit, zero section/column elements, no external files, native widget content placement, native critical visual settings, native style settings before CSS, preserved unrelated enhancements, mobile-first responsive settings, design-system markers, and html widgets enhancement-only. Read preflight, quality_summary, visual audits, repeated_agent_error_audit, and agent_conformance in responses and fix every failed repeated-agent check plus weak or blocked criteria before claiming completion; design quality gates require native heading hierarchy, native spacing, visible CTA, mobile-first responsive settings, deliberate palette, consistent design system, responsive unit policy, and populated native content. If any endpoint or verification step fails, include concrete error details in the response: endpoint/action, HTTP status or exception, plugin error code/message, details/preflight/blocking_errors, and the next safe fix. Use /logs for recent operation metadata when debugging; logs never include API keys, guide tokens, raw request bodies, raw page payloads, or secrets. Do not expose API keys.
PROMPT;
}

function wpae_elementor_page_snippet(): string {
    return <<<'PHP'
$page_id = wp_insert_post([
    'post_title'  => 'Landing Page',
    'post_name'   => 'landing-page',
    'post_status' => 'publish',
    'post_type'   => 'page',
], true);

if ( is_wp_error( $page_id ) ) {
    return [ 'ok' => false, 'error' => $page_id->get_error_message() ];
}

$elementor_data = [
    [
        'id'       => 'hero01',
        'elType'   => 'container',
        'isInner'  => false,
        'settings' => [
            'content_width'  => 'boxed',
            'flex_direction' => 'column',
        ],
        'elements' => [
            [
                'id'         => 'title01',
                'elType'     => 'widget',
                'widgetType' => 'heading',
                'isInner'    => false,
                'settings'   => [
                    'title'       => 'Landing headline',
                    'header_size' => 'h1',
                ],
                'elements'   => [],
            ],
        ],
    ],
];

update_post_meta( $page_id, '_elementor_edit_mode', 'builder' );
update_post_meta( $page_id, '_elementor_template_type', 'wp-page' );
update_post_meta( $page_id, '_elementor_version', defined( 'ELEMENTOR_VERSION' ) ? ELEMENTOR_VERSION : '' );
update_post_meta( $page_id, '_elementor_data', wp_slash( wp_json_encode( $elementor_data ) ) );
update_post_meta( $page_id, '_wp_page_template', 'elementor_canvas' );

return [ 'ok' => true, 'id' => $page_id, 'url' => get_permalink( $page_id ) ];
PHP;
}
