<?php

defined( 'ABSPATH' ) || exit;

return [
    [
        'id' => 'copyelement-image-box-c2644',
        'file' => 'image-box-c2644.json',
        'sha256' => '9c396b28525f14a33184ab30575605580d2498264fa87e1b1b92ec8d1ca97f43',
        'title' => 'Image Box c2644',
        'description' => "CopyElement's Wireframe - Image Box c2644.",
        'category' => 'image-box',
        'tags' => [ 'copyelement', 'wireframe', 'image-box', 'bento' ],
        'source_url' => 'https://copyelement.com/components/image-box/image-box-c2644',
        'preview_url' => 'https://utfs.io/f/e83guS7CoRXfmsezycUoeLCKrNUO6AjBtbwTIRxJl3cgZ4a5',
    ],
    [
        'id' => 'copyelement-testimonials-c1198',
        'file' => 'testimonials-c1198.json',
        'sha256' => '5cd088630371e015e046dec4d532337e7e421dcba7d010862ed4a18dfeb18c7e',
        'title' => 'Testimonials c1198',
        'description' => "CopyElement's Wireframe - Testimonials c1198.",
        'category' => 'testimonials',
        'tags' => [ 'copyelement', 'wireframe', 'testimonials', 'reviews', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-about-c70',
        'file' => 'about-c70.json',
        'sha256' => '33583fb531cec389f699d44547e5135dcd718235b16390398841b3e5f87ea7bf',
        'title' => 'About c70',
        'description' => "CopyElement's Wireframe - About c70.",
        'category' => 'about',
        'tags' => [ 'copyelement', 'wireframe', 'about', 'company', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-team-c1429',
        'file' => 'team-c1429.json',
        'sha256' => 'ec2835357a6582d0157fb18b9427c3835884aabb9f1c5f72db261ce1e8a0c1a6',
        'title' => 'Team c1429',
        'description' => "CopyElement's Wireframe - Team c1429.",
        'category' => 'team',
        'tags' => [ 'copyelement', 'wireframe', 'team', 'about', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-mega-menu-c3372',
        'file' => 'mega-menu-c3372.json',
        'sha256' => 'ff441f4c9eb4b5d31862e63bcc0ef910b3bc4475f613f101711e6af286302b30',
        'title' => 'Mega Menu c3372',
        'description' => "CopyElement's Wireframe - Mega Menu c3372.",
        'category' => 'mega-menu',
        'tags' => [ 'copyelement', 'wireframe', 'mega-menu', 'navigation', 'header', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_file' => 'assets/previews/mega-menu-c3372.png',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-404',
        'file' => 'vocario-404.json',
        'sha256' => '59fb0aaaa680e8cf8a22468d07eebb984da56ae7e321a342675f10284ba40af6',
        'title' => 'Vocario 404',
        'description' => 'Vocario Public Speaking Class template kit - 404.',
        'category' => '404',
        'tags' => [ 'vocario', 'template-kit', '404', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/404/',
        'preview_file' => 'assets/previews/vocario-404.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-home',
        'file' => 'vocario-home.json',
        'sha256' => 'df26f744a05877cf3965f84f800ab6649624451c4ed1ed4ad4333003dcd3b78e',
        'title' => 'Vocario Home',
        'description' => 'Vocario Public Speaking Class template kit - Home.',
        'category' => 'home',
        'tags' => [ 'vocario', 'template-kit', 'home', 'hero', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/home/',
        'preview_file' => 'assets/previews/vocario-home.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-about-us',
        'file' => 'vocario-about-us.json',
        'sha256' => 'aaa7e54e1448e84351ec8561f269a28989e464742ca7cc001b64733619eea058',
        'title' => 'Vocario About Us',
        'description' => 'Vocario Public Speaking Class template kit - About Us.',
        'category' => 'about',
        'tags' => [ 'vocario', 'template-kit', 'about', 'benefits', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/about-us/',
        'preview_file' => 'assets/previews/vocario-about-us.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-our-team',
        'file' => 'vocario-our-team.json',
        'sha256' => '79fee4747f620bd6dd5024cb831a25ec931704e4605228f506533117d8bf6002',
        'title' => 'Vocario Our Team',
        'description' => 'Vocario Public Speaking Class template kit - Our Team.',
        'category' => 'team',
        'tags' => [ 'vocario', 'template-kit', 'team', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/our-team/',
        'preview_file' => 'assets/previews/vocario-our-team.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-courses',
        'file' => 'vocario-courses.json',
        'sha256' => '4b88ba8a72f913de523bd3ad90b3d8b86c6cdeb6a27a63c5693f109acd28ace7',
        'title' => 'Vocario Courses',
        'description' => 'Vocario Public Speaking Class template kit - Courses.',
        'category' => 'courses',
        'tags' => [ 'vocario', 'template-kit', 'courses', 'benefits', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/courses/',
        'preview_file' => 'assets/previews/vocario-courses.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-upcoming-event',
        'file' => 'vocario-upcoming-event.json',
        'sha256' => 'df4a405c8c6845e644378b92de875a7eae0f25cf690f8ad9420f64a27078ddc8',
        'title' => 'Vocario Upcoming Event',
        'description' => 'Vocario Public Speaking Class template kit - Upcoming Event.',
        'category' => 'events',
        'tags' => [ 'vocario', 'template-kit', 'events', 'process', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/upcoming-event/',
        'preview_file' => 'assets/previews/vocario-upcoming-event.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-pricing',
        'file' => 'vocario-pricing.json',
        'sha256' => 'a7747e9f947996917166b6bf768af6c0fa698e8db6e17b549c40676ddac0e439',
        'title' => 'Vocario Pricing',
        'description' => 'Vocario Public Speaking Class template kit - Pricing.',
        'category' => 'pricing',
        'tags' => [ 'vocario', 'template-kit', 'pricing', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/pricing/',
        'preview_file' => 'assets/previews/vocario-pricing.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-blog',
        'file' => 'vocario-blog.json',
        'sha256' => '23d1cf461d28cbdb90225da008fa651dbafc297cc2dd07f89fa680c7e330905f',
        'title' => 'Vocario Blog',
        'description' => 'Vocario Public Speaking Class template kit - Blog.',
        'category' => 'blog',
        'tags' => [ 'vocario', 'template-kit', 'blog', 'portfolio', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/blog/',
        'preview_file' => 'assets/previews/vocario-blog.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-faq',
        'file' => 'vocario-faq.json',
        'sha256' => 'a16a04ca01707a3522b01c1bf6f9ce527cc5806b60933f7a2fe3bc459e195642',
        'title' => 'Vocario FAQ',
        'description' => 'Vocario Public Speaking Class template kit - FAQ.',
        'category' => 'faq',
        'tags' => [ 'vocario', 'template-kit', 'faq', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/faq/',
        'preview_file' => 'assets/previews/vocario-faq.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-contact-us',
        'file' => 'vocario-contact-us.json',
        'sha256' => '277cda7b1b7880a9c047d2c2cbdaf1a4d7589c4f63ce676006e2c8d5b832dbd4',
        'title' => 'Vocario Contact Us',
        'description' => 'Vocario Public Speaking Class template kit - Contact Us.',
        'category' => 'contact',
        'tags' => [ 'vocario', 'template-kit', 'contact', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/contact-us/',
        'preview_file' => 'assets/previews/vocario-contact-us.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-contact-us-form',
        'file' => 'vocario-contact-us-form.json',
        'sha256' => 'f8c9aa26efd9d02290a908d68d50961ccfc3285b89d31effa21937d3d9030d83',
        'title' => 'Vocario Contact Us Form',
        'description' => 'Vocario Public Speaking Class template kit - Contact Us Form.',
        'category' => 'contact-form',
        'tags' => [ 'vocario', 'template-kit', 'contact-form', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/contact-us-form/',
        'preview_file' => 'assets/previews/vocario-contact-us-form.png',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-header',
        'file' => 'vocario-header.json',
        'sha256' => 'abd3e9ed3f9cbfc59a90c35372bffc0f5554c866b6aea0965bacd80fbff517c4',
        'title' => 'Vocario Header',
        'description' => 'Vocario Public Speaking Class template kit - Header.',
        'category' => 'header',
        'tags' => [ 'vocario', 'template-kit', 'header', 'mega-menu', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/header/',
        'preview_file' => 'assets/previews/vocario-header.png',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-footer',
        'file' => 'vocario-footer.json',
        'sha256' => 'f204f263993833d2dac8e8bf0f50ae9c0d8b683607f31cac82fac43ced8ae8de',
        'title' => 'Vocario Footer',
        'description' => 'Vocario Public Speaking Class template kit - Footer.',
        'category' => 'footer',
        'tags' => [ 'vocario', 'template-kit', 'footer', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/footer/',
        'preview_file' => 'assets/previews/vocario-footer.png',
        'preview_url' => '',
    ],
];
