<?php

defined( 'ABSPATH' ) || exit;

return [
    [
        'id' => 'copyelement-image-box-c2644',
        'file' => 'image-box-c2644.json',
        'sha256' => '9c396b28525f14a33184ab30575605580d2498264fa87e1b1b92ec8d1ca97f43',
        'title' => 'Image Box c2644',
        'description' => "CopyElement's Wireframe - Image Box c2644.",
        'category' => 'image-box',
        'tags' => [ 'copyelement', 'wireframe', 'image-box', 'bento' ],
        'source_url' => 'https://copyelement.com/components/image-box/image-box-c2644',
        'preview_url' => 'https://utfs.io/f/e83guS7CoRXfmsezycUoeLCKrNUO6AjBtbwTIRxJl3cgZ4a5',
    ],
    [
        'id' => 'copyelement-testimonials-c1198',
        'file' => 'testimonials-c1198.json',
        'sha256' => '5cd088630371e015e046dec4d532337e7e421dcba7d010862ed4a18dfeb18c7e',
        'title' => 'Testimonials c1198',
        'description' => "CopyElement's Wireframe - Testimonials c1198.",
        'category' => 'testimonials',
        'tags' => [ 'copyelement', 'wireframe', 'testimonials', 'reviews', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-about-c70',
        'file' => 'about-c70.json',
        'sha256' => '33583fb531cec389f699d44547e5135dcd718235b16390398841b3e5f87ea7bf',
        'title' => 'About c70',
        'description' => "CopyElement's Wireframe - About c70.",
        'category' => 'about',
        'tags' => [ 'copyelement', 'wireframe', 'about', 'company', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-team-c1429',
        'file' => 'team-c1429.json',
        'sha256' => 'ec2835357a6582d0157fb18b9427c3835884aabb9f1c5f72db261ce1e8a0c1a6',
        'title' => 'Team c1429',
        'description' => "CopyElement's Wireframe - Team c1429.",
        'category' => 'team',
        'tags' => [ 'copyelement', 'wireframe', 'team', 'about', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-mega-menu-c3372',
        'file' => 'mega-menu-c3372.json',
        'sha256' => 'ff441f4c9eb4b5d31862e63bcc0ef910b3bc4475f613f101711e6af286302b30',
        'title' => 'Mega Menu c3372',
        'description' => "CopyElement's Wireframe - Mega Menu c3372.",
        'category' => 'mega-menu',
        'tags' => [ 'copyelement', 'wireframe', 'mega-menu', 'navigation', 'header', 'bento' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_file' => 'assets/previews/mega-menu-c3372.png',
        'preview_url' => '',
    ],
    [
        'id' => 'copyelement-image-carousel-a4516bb',
        'file' => 'image-carousel-a4516bb.json',
        'sha256' => 'adce53f13e2bff9b0ca5744515a980e043334124e03f32ac24e285d12c34f376',
        'title' => 'Image Carousel a4516bb',
        'description' => "CopyElement's Image Carousel with five visual slides.",
        'category' => 'carousel',
        'tags' => [ 'copyelement', 'carousel', 'image-carousel', 'logos', 'partners' ],
        'source_url' => 'https://copyelement.com/components/free',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-404',
        'file' => 'vocario-404.json',
        'sha256' => '4766652b63ba30dc62d0e40674d2f28a914601c9b1e034c4b9db9a678ad5b8a1',
        'title' => 'Vocario 404',
        'description' => 'Vocario Public Speaking Class template kit - 404.',
        'category' => '404',
        'tags' => [ 'vocario', 'template-kit', '404', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/404/',
        'preview_file' => 'assets/previews/vocario-404.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-home',
        'file' => 'vocario-home.json',
        'sha256' => '80ac99c4a7b3b3ea0676c0e49999c2e2c87beb100117474250d2b4ce47150dcc',
        'title' => 'Vocario Home',
        'description' => 'Vocario Public Speaking Class template kit - Home.',
        'category' => 'home',
        'tags' => [ 'vocario', 'template-kit', 'home', 'hero', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/home/',
        'preview_file' => 'assets/previews/vocario-home.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-about-us',
        'file' => 'vocario-about-us.json',
        'sha256' => '9190d6c51e322c20a2de6a47f380c9b7607aafb14cb489e7f31227ea3d43a2d8',
        'title' => 'Vocario About Us',
        'description' => 'Vocario Public Speaking Class template kit - About Us.',
        'category' => 'about',
        'tags' => [ 'vocario', 'template-kit', 'about', 'benefits', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/about-us/',
        'preview_file' => 'assets/previews/vocario-about-us.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-our-team',
        'file' => 'vocario-our-team.json',
        'sha256' => '8fe6bb9cb3548de7dda15d4783603bb885f60aacaa62587f40443f2bfc76a959',
        'title' => 'Vocario Our Team',
        'description' => 'Vocario Public Speaking Class template kit - Our Team.',
        'category' => 'team',
        'tags' => [ 'vocario', 'template-kit', 'team', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/our-team/',
        'preview_file' => 'assets/previews/vocario-our-team.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-courses',
        'file' => 'vocario-courses.json',
        'sha256' => 'fb59d66eb60ff67fda245c7f8bf885a2738a1df784d2733d5a9e5292aead5073',
        'title' => 'Vocario Courses',
        'description' => 'Vocario Public Speaking Class template kit - Courses.',
        'category' => 'courses',
        'tags' => [ 'vocario', 'template-kit', 'courses', 'benefits', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/courses/',
        'preview_file' => 'assets/previews/vocario-courses.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-upcoming-event',
        'file' => 'vocario-upcoming-event.json',
        'sha256' => '70522de8aa09ca1c0ecf2093673b1cade407f81ae34b92abd100bc867bb75751',
        'title' => 'Vocario Upcoming Event',
        'description' => 'Vocario Public Speaking Class template kit - Upcoming Event.',
        'category' => 'events',
        'tags' => [ 'vocario', 'template-kit', 'events', 'process', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/upcoming-event/',
        'preview_file' => 'assets/previews/vocario-upcoming-event.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-pricing',
        'file' => 'vocario-pricing.json',
        'sha256' => '6fbf001486346dc87e0442f2bf54892fc5ba3db548a8aaa146469ddc28abae9b',
        'title' => 'Vocario Pricing',
        'description' => 'Vocario Public Speaking Class template kit - Pricing.',
        'category' => 'pricing',
        'tags' => [ 'vocario', 'template-kit', 'pricing', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/pricing/',
        'preview_file' => 'assets/previews/vocario-pricing.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-blog',
        'file' => 'vocario-blog.json',
        'sha256' => '1cf6e05b8ea2ea7e2ca3c2ed9e483359a9eee691156208e80ce77a0d19fd59fd',
        'title' => 'Vocario Blog',
        'description' => 'Vocario Public Speaking Class template kit - Blog.',
        'category' => 'blog',
        'tags' => [ 'vocario', 'template-kit', 'blog', 'portfolio', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/blog/',
        'preview_file' => 'assets/previews/vocario-blog.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-faq',
        'file' => 'vocario-faq.json',
        'sha256' => '1142807204358582562e8f93caeec9c878339ebf21ae52540ca1dc0faca4efc3',
        'title' => 'Vocario FAQ',
        'description' => 'Vocario Public Speaking Class template kit - FAQ.',
        'category' => 'faq',
        'tags' => [ 'vocario', 'template-kit', 'faq', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/faq/',
        'preview_file' => 'assets/previews/vocario-faq.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-contact-us',
        'file' => 'vocario-contact-us.json',
        'sha256' => 'b6ebc4cd1e2d180cfdd80d245dc47a42a184e33e88e3f16be7d618c928b6be26',
        'title' => 'Vocario Contact Us',
        'description' => 'Vocario Public Speaking Class template kit - Contact Us.',
        'category' => 'contact',
        'tags' => [ 'vocario', 'template-kit', 'contact', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/contact-us/',
        'preview_file' => 'assets/previews/vocario-contact-us.jpg',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-contact-us-form',
        'file' => 'vocario-contact-us-form.json',
        'sha256' => '2c4a43515f23f3fba7ad163d3d9689395bf998ab9684f35402af8940a8d129fd',
        'title' => 'Vocario Contact Us Form',
        'description' => 'Vocario Public Speaking Class template kit - Contact Us Form.',
        'category' => 'contact-form',
        'tags' => [ 'vocario', 'template-kit', 'contact-form', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/contact-us-form/',
        'preview_file' => 'assets/previews/vocario-contact-us-form.png',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-header',
        'file' => 'vocario-header.json',
        'sha256' => '6af07490c501a321b879f0ad267e86d2916bc39f8f10cddf8ffc63acf7e664e0',
        'title' => 'Vocario Header',
        'description' => 'Vocario Public Speaking Class template kit - Header.',
        'category' => 'header',
        'tags' => [ 'vocario', 'template-kit', 'header', 'mega-menu', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/header/',
        'preview_file' => 'assets/previews/vocario-header.png',
        'preview_url' => '',
    ],
    [
        'id' => 'vocario-footer',
        'file' => 'vocario-footer.json',
        'sha256' => '69d3c19d76d7a56e0c556fad94a99ed21be3b5d22be58f2070e2e93ec43aeffd',
        'title' => 'Vocario Footer',
        'description' => 'Vocario Public Speaking Class template kit - Footer.',
        'category' => 'footer',
        'tags' => [ 'vocario', 'template-kit', 'footer', 'cta', 'bento' ],
        'source_url' => 'https://templatekit.kitprostudio.com/vocario/template-kit/footer/',
        'preview_file' => 'assets/previews/vocario-footer.png',
        'preview_url' => '',
    ],
];
